### ISSUE TITLE
Installation of Weblets

### ISSUE THREAD

**Issue by dmitri-alleo** [threefoldtech/test_feedback#10]
Installing Weblet on a remote server (testing time: 1.5 hour)
Tried different configs and OS,
1 Vcpu, 2GM RAM, OS -> CentOS 7
2 Vcpu,42GM RAM, OS -> CentOS 7

1 Vcpu, 2GM RAM, OS -> Ubuntu 20
2 Vcpu,42GM RAM, OS -> Ubuntu 20

```
Installation fails with:
FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory
```

**Comment by abom** [comment]
Please have a look at weblets documentation [here](https://github.com/threefoldtech/grid_weblets#installation), specially this part:

> 
> JavaScript heap out of memory error:
> 
> In some cases you could see an error like this: FATAL ERROR: Reached heap limit Allocation failed - JavaScript heap out of memory
> 
> As Rollup needs to keep all module information in memory simultaneously to be able to analyze relevant side effects for tree-shaking, it is possible that bundling large projects reaches Node's memory limit. If this happens, it can help to increase this limit by running Rollup via
> 
> export NODE_OPTIONS="--max-old-space-size=2048" # or even higher size 8192
> yarn build:app # on grid_weblets (dir)
> Increasing --max-old-space-size as needed. Note that this number can safely surpass your available physical memory. In that case, Node will start paging memory to disk as needed.
