### ISSUE TITLE
Buying TFT with Eur

### ISSUE THREAD

**Issue by dmitri-alleo** [threefoldtech/test_feedback#110]
On the test website, when entering the Stellar address, getting this error,
On the live website this step works and goes to the step where you can enter payment details, so the issue is not with the address

![image](https://user-images.githubusercontent.com/65153287/164439915-b75ac70e-7b54-46b2-b8b9-5cf20cee78d5.png)

![image](https://user-images.githubusercontent.com/65153287/164440278-a23f7875-4503-4dcb-8575-6351772b255b.png)

**Comment by dmitri-alleo** [comment]
The site URL is https://test.gettft.com/gettft/

**Comment by xmonader** [comment]
You can't use `mainnet stellar` addresses on the test.gettft.com website
