### ISSUE TITLE
Buying TFT with BTC Mainnet (Add copy button to the amount)

### ISSUE THREAD

**Issue by dmitri-alleo** [threefoldtech/test_feedback#121]
This is not a bug, rather a UX issue,

When the amount to be sent is specified to the user, like in many other payment gateways - you can copy the address, but you cannot copy the amount, which makes the user type the amount that needs to be sent, and may possibly result in the wrong amount due to a human error:

![image](https://user-images.githubusercontent.com/65153287/166922937-546ebaad-3c06-4a35-859b-c7585000d9b4.png)

**Comment by xmonader** [comment]
Will be on the next live version
