### ISSUE TITLE
Deploying QSFS with Terraform

### ISSUE THREAD

**Issue by dmitri-alleo** [threefoldtech/test_feedback#124]
Duration: 80 min

1. Deploying QSFS  via terraform fails with:

```
│ Error: failed to fetch nodes from the grid proxy: json: cannot unmarshal number into Go struct field Node.updatedAt of type string
│ 
│   with grid_network.net1,
│   on main.tf line 18, in resource "grid_network" "net1":
│   18: resource "grid_network" "net1" {
│ 
╵
╷
│ Error: failed to fetch nodes from the grid proxy: json: cannot unmarshal number into Go struct field Node.updatedAt of type string
│ 
│   with grid_deployment.d1,
│   on main.tf line 25, in resource "grid_deployment" "d1":
│   25: resource "grid_deployment" "d1" {
```

Deployed via "terraform-provide-grid" examples/resources/qsfs

2. Also, tried deploying via tests/SQFS, the deploy was successful, but the node wasn't accessible, Ygg IP didn't get created

WORKING SOLUTION
3. Managed to configure, install and run by deploying a VM and installing manually  by using the guide in the documentation https://github.com/threefoldfoundation/info_threefold_pub/blob/main/wiki/qss/manual/qsfs_setup.md

**Comment by xmonader** [comment]
@ramezsaeed please track as part of qsfs issues to verify
