### ISSUE TITLE
OwnCloud video playback

### ISSUE THREAD

**Issue by dmitri-alleo** [threefoldtech/test_feedback#126]
Uploaded a video to OwnCloud and trying to playback. The video is 655 MB and 3 minutes long, HD.
Buffering is very slow and takes several minutes to play a few seconds of the video.

I believe this is related to the overall Grid speed and performance.
Please advise if this can be improved

**Comment by dmitri-alleo** [comment]
This was on the Testnet with the OwnCloud deployer instance for alpha 5 testing

**Comment by dmitri-alleo** [comment]
Tested the same on the Weblets, deployed on the Node(3) on Testnet,
The same very HQ video also doesn't play, but a smaller mp4 video plays without any issues

**Comment by ramezsaeed** [comment]
@delandtj Please check
