### ISSUE TITLE
Request OwnCloud instance - 4-letter domain

### ISSUE THREAD

**Issue by dmitri-alleo** [threefoldtech/test_feedback#128]
The issue was reported earlier, don't see it in the test_feedback, but the issue is still not resolved.
The email validation doesn't work with the email addresses ending in domain with more than 3-letters

![image](https://user-images.githubusercontent.com/65153287/167915619-32edc3c1-8a42-41d8-a868-7ae6319381e4.png)

**Comment by xmonader** [comment]
duplicate https://github.com/threefoldtech/owncloud_deployer/issues/26
