### ISSUE TITLE
Accessing instance with davs

### ISSUE THREAD

**Issue by dmitri-alleo** [threefoldtech/test_feedback#130]
When trying to connect to OwnCloud via files with davs, (distro: Linux Mint 20)

 getting this error

![image](https://user-images.githubusercontent.com/65153287/167925560-76659a02-e75a-4a13-86dd-cb64b3e9d130.png)

**Comment by dmitri-alleo** [comment]
Tried with port 443 as well, the result is the same,

this is a default viewer

**Comment by xmonader** [comment]
@sameh-farouk

**Comment by sameh-farouk** [comment]
@dmitri-alleo what is the exact full address you are trying to connect to? it seems you used an incorrect URL.

the correct URL can be found on your Owncloud dashboard, at the bottom left corner.

![Screenshot from 2022-05-12 12-13-35](https://user-images.githubusercontent.com/42457449/168048219-c0a40055-969e-4b8a-bbfe-e0676e454d02.png)

**Comment by sameh-farouk** [comment]
also, could you execute this command from the terminal and provide the full output:
```sh
curl -u "<USERNAME>:<PASSWORD>" -v -X MKCOL "https://<DOMAIN>/remote.php/dav/files/<USERNAME>/$(date '+%d-%b-%Y')"
```
this, if succeeded should create a new folder in your Owncloud files with the current date as a name.

**Comment by sameh-farouk** [comment]
worth mentioning that Owncloud [admin manual](https://doc.owncloud.com/webui/next/classic_ui/files/access_webdav.html#accessing-files-using-linux) assumes that the ownCloud server is already accessible under the route `/owncloud`. from their docs:

> Nautilus File Manager
Use the davs:// protocol to connect the Nautilus file manager to your ownCloud share:
davs://example.com/**owncloud**/remote.php/webdav

**but this is not irrelevant to our setup, and if used will cause the redirection error you experienced before. you should instead use `davs://example.com/remote.php/webdav`.**

**Comment by dmitri-alleo** [comment]
I have tried to login with the URL specified at the bottom of the screen,
tried http -> ports 80 and 443
tried dav and davs -> port 80 and 443

![image](https://user-images.githubusercontent.com/65153287/168077142-77626324-2e38-4bf8-808e-f073acb36808.png)

When running the "curl" command, at first got an error, but I've realised that I've 2 exclamation marks as !! in the password, so it was throwing an error, but after I have changed the password and removed the exclamation marks, it has created the directory successfully.

In the end managed to connect with Nautilus via davs://, as I don't have it by default as my environment is not Gnome 
Thank you @sameh-farouk

**Comment by dmitri-alleo** [comment]
Originally used Caja as the file manager, it has multiple options including davs connection, but only worked out with Nautilus

**Comment by sameh-farouk** [comment]
> When running the "curl" command, at first got an error, but I've realised that I've 2 exclamation marks as !! in the password, so it was throwing an error, but after I have changed the password and removed the exclamation marks, it has created the directory successfully.

I'm happy you were able to work around this. I think you could use your old password with `curl` command, but you will have to use single quotes instead of the double-quotes.

```sh
curl -u '<USERNAME>:<PASSWORD>' -v -X MKCOL "https://<DOMAIN>/remote.php/dav/files/<USERNAME>/$(date '+%d-%b-%Y')"
```
but I didn't test that :D
