### ISSUE TITLE
OwnCloud - 404 page not found

### ISSUE THREAD

**Issue by dmitri-alleo** [threefoldtech/test_feedback#141]
Everything was working until the after lunch time today, but at some point started failing with the 404 Not Found

OwnCloud URL: https://ownclouddimitrialleoubj.gent01.test.grid.tf/

![image](https://user-images.githubusercontent.com/65153287/168305090-29c8f1d2-f883-4365-b938-0e8febbccfde.png)

**Comment by sameh-farouk** [comment]
DevOps wallet on testnet ran out of tokens yesterday, All deployments and names owned by this account were canceled and you are seeing this error because this subdomain does not exist anymore.
