### ISSUE TITLE
Deploying Kubernets with Terraform

### ISSUE THREAD

**Issue by dmitri-alleo** [threefoldtech/test_feedback#142]
After the deployment getting an error:
```
grid_network.net1: Refreshing state... [id=8e4079c3-41fc-48aa-8ceb-fa782434f197]
╷
│ Error: couldn't invalidate broken attributes: couldn't get node 7 contract 3761: unknown version
│ 
│   with grid_network.net1,
│   on main.tf line 20, in resource "grid_network" "net1":
│   20: resource "grid_network" "net1" {
│ 
```

The commands used on the deployment of "terraform-provider-grid/tests/kubernetes" were
```
terraform init && terraform apply -parallelism=1
```

The public key, mnemonics, network all configured, 
tried different nodes in nodex = [x, x] -> same output
each time the test is deployed, trying to get the node for contracts 3761 - 3763

**Comment by dmitri-alleo** [comment]
The repo branch used is the same as before: development_terratests

**Comment by xmonader** [comment]
Why would you be using the development_terratests branch instead of a released version!?

**Comment by dmitri-alleo** [comment]
@xmonader should it be v0.1.32?

**Comment by xmonader** [comment]
Yes
