### ISSUE TITLE
Purchase TFT with fiat - Mainnet (UX flaw)

### ISSUE THREAD

**Issue by dmitri-alleo** [threefoldtech/test_feedback#149]
The test result was a success, but there were a few things in the UX flow
most likely we don't control the process, but wasn't aware of the exact steps and also notifications in the process were not clear

1. Didn't expect that will need to pass KYC for 100 Eur purchase
2. After submitting the KYC it takes you back to the credit card form screen, but the form gets reset and payment fee changes, either based on the country or the TFT price, but it differed from the original by 1 - 1.5 Euros higher
3. After submitting the payment it shows the screen with payment receipt and link: the transaction ID, if you open it in the new window, it shows a blank screen, so once clicking on the screen with the receipt, it tries opening the link in the same window, but again loads a blank screen. If I tried going back to the previous page, it was only showing a loader and it would not show the receipt or links information, so at that moment I wasn't sure what was the status of the payment for around 20 minutes until the funds arrived to the wallet

**Comment by dmitri-alleo** [comment]
The purchase flow itself was tested on both Testnet and Mainnet and was a success, for BTC and Fiat purchases:
Testnet: https://test.gettft.com/gettft/
Mainnet: https://gettft.com/gettft/

Also, have tested the fields for errors and validations

disregarding a UX flow described at the top (I guess depending on which platform you use, starting from which amounts you need to pass KYC etc, the flow is still quite standard)

**Comment by ramezsaeed** [comment]
@nbabenko please review and track this one
