### ISSUE TITLE
No.11 - Test case: TC443 (owncloud instance bad gateway)

### ISSUE THREAD

**Issue by dmitri-alleo** [threefoldtech/test_feedback#156]
vers - v1.4.1-rc2

 Deployed, but at the same time 502 error  when clicking on the link
![image](https://user-images.githubusercontent.com/65153287/169024549-d891b440-07c9-4bef-a13b-4fe6fe1a1a9f.png)

**Comment by xmonader** [comment]
is that still the case? we resolved the root cause of that which was the ulimits? if the problem still happens on new instances please reopen.

**Comment by dmitri-alleo** [comment]
I`ve deleted  Contracts List and now it`s work

**Comment by dmitri-alleo** [comment]
yeeep , now it works
