### ISSUE TITLE
OwnCloud deployer - the account credentials never came

### ISSUE THREAD

**Issue by dmitri-alleo** [threefoldtech/test_feedback#160]
Trying to request with different email, cannot submit for different email with the same user,
the credentials for previous request never came

![image](https://user-images.githubusercontent.com/65153287/169107409-0bdee0e1-60b0-4ffb-a7c4-ed7265cc16e3.png)

**Comment by xmonader** [comment]
@hossnys please double check on the existing pending requests.

**Comment by mohamedamer453** [comment]
Done.

![image](https://user-images.githubusercontent.com/101194226/169247905-15bd67e9-0299-499f-ae11-4d9934205c87.png)

**Comment by hossnys** [comment]
> @hossnys please double check on the existing pending requests.

i think that @dmitri-alleo have admin access to that instance , so he approve his request to test the full scenario , but let me approve all coming requests from now on .

**Comment by dmitri-alleo** [comment]
Yes got the login details, thanks.
But I'm not sure how can I login into the admin to approve my own requests,
thanks

**Comment by hossnys** [comment]
> Yes got the login details, thanks. But I'm not sure how can I login into the admin to approve my own requests, thanks

https://ownclouddeployer.test.grid.tf/owncloud/#/requests from here you can approve you requests

**Comment by dmitri-alleo** [comment]
Great! Thanks a lot @hossnys
