### ISSUE TITLE
when scanning from the portal with tfconnect  I get "no balance on object"

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/test_feedback#184]
when I scan QR code to bring money to tfchain, it gives me error on javascript wallet tfconnect, no balance on object ...

![image](https://user-images.githubusercontent.com/64129/170852024-62b1998d-2cfe-4534-8208-b4fe795ae06c.png)

reported by @despiegk also happened with me

**Comment by xmonader** [comment]
please follow up here @ken-de-moor

**Comment by ken-de-moor** [comment]
It's a wrong allert, it can be clicked away and you can just continue. Happens only in specific scenarios(won't happen to people who only have app generated wallets). Fix is already ready on local version and will be included in next wallet version.

https://github.com/threefoldtech/wallet-next/issues/158

**Comment by ken-de-moor** [comment]
Fixed and being deployed today. Personally validated on beta.

Release was awaiting vesting API from Rob but we did a smaller release to include bugs in the meantime.
