### ISSUE TITLE
TC734 -  Make sure you can use cloud-init with ZOS VMs 

### ISSUE THREAD

**Issue by dmitri-alleo** [threefoldtech/test_feedback#189]
Failed during the Terraform deployments of the VM's with current flists:

Flists

https://hub.grid.tf/azmy.3bot/archlinux.flist
```
│ Error: error waiting deployment: workload 1 failed within deployment 5665 with error at least one mount has to be attached for Vm mode
│ 
│   with grid_deployment.d1,
│   on main.tf line 32, in resource "grid_deployment" "d1":
│   32: resource "grid_deployment" "d1" {
```

https://hub.grid.tf/azmy.3bot/ubuntu-18.04-lts.flist
```
│ Error: error waiting deployment: workload 0 failed within deployment 5668 with error at least one mount has to be attached for Vm mode
│ 
│   with grid_deployment.d1,
│   on main.tf line 32, in resource "grid_deployment" "d1":
│   32: resource "grid_deployment" "d1" {
```

https://hub.grid.tf/azmy.3bot/ubuntu-20.04-lts.flist
```
│ Error: error waiting deployment: workload 0 failed within deployment 5668 with error at least one mount has to be attached for Vm mode
│ 
│   with grid_deployment.d1,
│   on main.tf line 32, in resource "grid_deployment" "d1":
│   32: resource "grid_deployment" "d1" {
```

https://hub.grid.tf/azmy.3bot/ubuntu-22.04.flist
```
│ Error: error waiting deployment: workload 0 failed within deployment 5668 with error at least one mount has to be attached for Vm mode
│ 
│   with grid_deployment.d1,
│   on main.tf line 32, in resource "grid_deployment" "d1":
│   32: resource "grid_deployment" "d1" {
```

Deployed on Testner
Grid provider v0.1.32

**Comment by muhamadazmy** [comment]
There are 2 flist formats supported for a ZMachine workload
- Container flist, this is an flist that contains `files` similar to docker image. When that is used there no `need` for an extra disk to be attached to the zmachine. Any extra disk is mounted as data disk based on the zmahcine workload mount config.
- A VM flist, this one include an `image.raw` file only. This include a full cloud-init enabled vm image (including kernel, etc...) so this to be used by zos need to be copied to a virtual disk. Hence the deployment needs at least one attached disk to the VM
