### ISSUE TITLE
TC737 - Log in to Uhuru

### ISSUE THREAD

**Issue by dmitri-alleo** [threefoldtech/test_feedback#190]
When trying to login to Uhuru with my ThreeFold Connect app, getting the error that the account doesn't yet exist

![image](https://user-images.githubusercontent.com/65153287/171365328-2349147d-b9fb-46af-9b82-b6be0f2dd5fe.png)

**Comment by ramezsaeed** [comment]
@ken-de-moor

**Comment by ken-de-moor** [comment]
@ramezsaeed could we got some more info?

What env/url is this, what is the user's 3botname exactly? Any console logs/network calls? Any repro steps to trigger this?

**Comment by ken-de-moor** [comment]
Just checked on my end, the account dmitrialleo simply doesn't exist on TF connect, so the error is normal.

First you need to create a TF connect account before logging in. The error clearly communicates this as well.

**Comment by dmitri-alleo** [comment]
@ken-de-moor yes, you are right,
my apologies, it's dimitrialleo,
Now I have managed to log in, will test from there on
