### ISSUE TITLE
The resource not satisfy the package details as were described in the options specification 

### ISSUE THREAD

**Issue by VenyaPanou** [threefoldtech/test_feedback#192]
Create ownCloud
when i select capacity package - Custom , i have this data : Disk (GB) 250 , but after deploy , i get tihs data : Disk (GB) 100
![image](https://user-images.githubusercontent.com/106578096/171377969-755fcfca-f05e-4d74-af9f-9a720e7151e6.png)
res: 
![image](https://user-images.githubusercontent.com/106578096/171378004-a2621964-c6fa-4c6b-bf95-c7bd7d96fa40.png)
No.27 - Test case: TC667
Version v1.4.2
Deployed on Testnet

**Comment by rkhamis** [comment]
should be fixed in 1.4.3

**Comment by rkhamis** [comment]
@VenyaPanou please verify when released

**Comment by ramezsaeed** [comment]
@AhmedHanafy725 
please notify once released on testnet

**Comment by dmitri-alleo** [comment]
Thanks, waiting

**Comment by AhmedHanafy725** [comment]
it's released on testnet

**Comment by mohamedamer453** [comment]
Verified on testnet.

I deployed an owncloud instance as originally mentioned in the issue with minimum package.

![image](https://user-images.githubusercontent.com/101194226/186365937-82444fb9-3205-48ce-af55-066902c518bf.png)

and after the deployment the specs were deployed as mentioned in the configuration 

![image](https://user-images.githubusercontent.com/101194226/186366574-8c783043-8298-4c93-a50b-fb77420f7959.png)
