### ISSUE TITLE
Add user flow to delete Farms 

### ISSUE THREAD

**Issue by VenyaPanou** [threefoldtech/test_feedback#198]
TF-Chain Portal on Devnet: https://portal.dev.grid.tf/
TF-Chain Portal on Testnet: https://portal.test.grid.tf/
Users can create farm , but what users will do , if they needed delete Farms ?
![image](https://user-images.githubusercontent.com/106578096/171398220-34deb97a-afe0-4875-8a97-26b98145b20e.png)

**Comment by rkhamis** [comment]
already in the new dashboard
