### ISSUE TITLE
Terraform deployment Error - failed to cancel/create contract: failed to submit extrinsic

### ISSUE THREAD

**Issue by luisanadal** [threefoldtech/test_feedback#208]
Hi, 
Almost every 1 out of 3 times I got the below error, forcing me to re-apply terraform, 

Error: failed to delete deployment: failed to cancel contract: failed to submit extrinsic: Priority is too low: (302300000 vs 302300000)

Using: 
    terraform v1.2.1
    nodes = 291, 294, 298 (but for what i have seen this is not related to the nodes themselves)

Best regards

**Comment by rkhamis** [comment]
if more than one deployment from the same account are taking place at the same time, it might happen.

you can use `--parallelism 1` if you are.

@luisanadal is this the case for you? please update this issue if this doesn't fix it or if there are no simultaneous deployments

**Comment by luisanadal** [comment]
let me check that, you might be right
