### ISSUE TITLE
Terrraform deployment error - Error: couldn't reach node X

### ISSUE THREAD

**Issue by luisanadal** [threefoldtech/test_feedback#210]
Hi,

Sometimes the node itself is in a weird state, it is running no errors shown, it is able to sync with the grid so it is up to date but i cannot deploy, i get the below error, this happened to me in a bunch of nodes, i have seen that after rebooting the node, all work just fine

 (Note:  ipv4 communication seems to be working just fine)

│ Error: couldn't reach node 	334: (400): {"status": "error", "message": "Post "http://300:59d7:c6b0:6d82:21bc:ce3d:7927:1ebc:8051/zbus-cmd": dial tcp [300:59d7:c6b0:6d82:21bc:ce3d:7927:1ebc]:8051: i/o timeout"}
│ 
│   with grid_network.net,
│   on streamr.tf line 21, in resource "grid_network" "net":
│   21: resource "grid_network" "net" {
│ 
╵

Using:
terraform v1.2.1

Best regards

**Comment by OmarElawady** [comment]
@coesensbert reported a similar behavior for a couple of nodes ("Node 292 and 478 from Farm 73"). Node 292 and 334 have a public ip but it's not pingable, and its ygg ip is not pingable. Terraform tries to validate at the beginning that it can reach the node and fails with this error.

It's possible that it's a problem with the network setup of the node (e.g. it blocks inbound traffic after sometime or something like this). Or it's an issue with zos that causes connectivity loss.

**Comment by luisanadal** [comment]
hello,

I dont think is a internal network issue, some nodes in the same
Datacenter, in the same rack and same network setup, work and others
don't, the interesting thing is if i reboot the node it start working,
so i guess is something in the node itlsef that ends up failing.

i can make some tests on those nodes that dont work, let me know which
nodes you want to test.

best regards
