### ISSUE TITLE
 Validation for "Amount" input does not work correctly.TF Chain Portal.Transfer page

### ISSUE THREAD

**Issue by VenyaPanou** [threefoldtech/test_feedback#213]
![screenshoteasy - 2022-06-03T152944 500](https://user-images.githubusercontent.com/106578096/171853899-ea31631a-10fa-4a8c-b17a-77d5334f5f49.png)

Number
No.384 - Test case: TC560

**Comment by rkhamis** [comment]
we're working on the dashboard. this should be handled there
