### ISSUE TITLE
Sorting is working no correctly in the Dedicated Nodes Table

### ISSUE THREAD

**Issue by VenyaPanou** [threefoldtech/test_feedback#217]
sorting works from the second click
![Peek 2022-06-04 11-35](https://user-images.githubusercontent.com/106578096/171991622-cd3156cd-7f0e-4b35-9823-2061f1cb27bf.gif)
No.376 - Test case: TC552
Version v1.4.2
Deployed on Testnet

**Comment by rkhamis** [comment]
the list is not sorted. so the fist click sorts it ascending, the seconds descending
