### ISSUE TITLE
simulator not right

### ISSUE THREAD

**Issue by despiegk** [threefoldtech/test_feedback#218]
<img width="1320" alt="image" src="https://user-images.githubusercontent.com/6021844/171991708-09617ded-78d7-4e66-b8c9-a740024f15ac.png">
CU should be much higher

**Comment by renauter** [comment]
CU formula is:

cu = min((mru - 1) / 4, cru * 4 / 2, sru / 50)

see ref here: https://library.threefold.me/info/threefold#/resource_units_calc_cloudunits
Obs: units are not clear in formula...

In above case we have
MRU = 120000 GB
CRU = 88888888 Threads
SRU = 1000 GB

So CU = 1000 / 50 = 20

Let s also check SU
su = hru / 1200 + sru * 0.8 / 200
SU = 0 + 1000* 0.8 / 200 = 4

Formulas seems to be well calculated

@despiegk  CU formula should be changed you mean?

**Comment by despiegk** [comment]
my bad, its ssd issue, will put more info on our wiki
