### ISSUE TITLE
Displayed Online Nodes when user turn off the online filter

### ISSUE THREAD

**Issue by VenyaPanou** [threefoldtech/test_feedback#220]
Testnet: https://explorer.test.grid.tf/
Devnet: https://explorer.dev.grid.tf/
![Peek 2022-06-04 14-15](https://user-images.githubusercontent.com/106578096/171996707-faa76cf8-c24a-4a3d-8663-b413c984a009.gif)

No.197 - Test case: TC392
Version v1.4.2
Deployed on Testnet

**Comment by rkhamis** [comment]
this means it's showing both online and offline nodes. not an issue
