### ISSUE TITLE
Didn't receive transferred TFTs on mainnet 

### ISSUE THREAD

**Issue by mohamedamer453** [threefoldtech/test_feedback#223]
approx. 1 hour ago i transferred  2x10 TFTs from my TFConnect wallet to 2 different accounts one on testnet (twin_537) and the other on mainnet (twin_5632) after about 50 min i received the TFTs on testnet (twin_537) but i didn't receive the ones i sent for mainnet (twin_5632)

Transaction details from setllar 

### [Testnet](https://stellar.expert/explorer/public/tx/176900915419308032#176900915419308034) (twin_537)

![image](https://user-images.githubusercontent.com/101194226/172055589-fae8fa29-ace2-448e-aef4-d69f695e95e5.png)

### [mainnet](https://stellar.expert/explorer/public/tx/176900893946155008#176900893946155010) (twin_5632)

![image](https://user-images.githubusercontent.com/101194226/172055565-5fbd8df8-4d11-4512-8782-97a50d5a1162.png)

the transactions can also be checked from my TFConnect wallet on stellar [here](https://stellar.expert/explorer/public/account/GBXZBZUGGAQWUG44AHDBYQ5I6ZL35BKVXBI233FUJVIAQJUG6IM2OP4J).

**Comment by mohamedamer453** [comment]
I checked the portal now and i received the tfts for `twin 5632` almost 24 hours after i transferred them.

**Comment by rkhamis** [comment]
@mohamedamer453 since this is now fixed, I'll close it. but please reopen if you see further issues
