### ISSUE TITLE
The link is not valid

### ISSUE THREAD

**Issue by VenyaPanou** [threefoldtech/test_feedback#226]
link : https://threefoldhub.test.gridtesting.xyz/ 
in cases : **TC567,TC569,TC570,TC571,TC572,TC573,TC753,TC574,TC624,TC625,TC626,TC627,TC576,TC577,TC628,TC629,TC630,TC578,TC579,TC580,TC752,TC581**
![screenshoteasy - 2022-06-07T111245 066](https://user-images.githubusercontent.com/106578096/172330439-1b791a61-2e32-49d1-8316-8c6c22032149.png)

**Comment by rkhamis** [comment]
the correct link is https://tfhub.test.grid.tf/
@VenyaPanou please update in all testcases

**Comment by mohamedamer453** [comment]
All [test cases](https://app.testlodge.com/a/26076/projects/40893/suites/204479) were updated with the new url.
