### ISSUE TITLE
Link is not working 404 error

### ISSUE THREAD

**Issue by VenyaPanou** [threefoldtech/test_feedback#229]
No.388 - Test case: TC740
https://github.com/threefoldtech/node-pilot-light#run
![image](https://user-images.githubusercontent.com/106578096/172774848-bf313a78-f82d-44b4-9284-7593dc2ceba7.png)

**Comment by ramezsaeed** [comment]
repo is private, no user documentation yet.

**Comment by ramezsaeed** [comment]
@maxux

**Comment by maxux** [comment]
This repository will probably die soon (at least will be cleared).

**Comment by dmitri-alleo** [comment]
Was able to access it anyway
