### ISSUE TITLE
TC261.Error when Scanning QR Code

### ISSUE THREAD

**Issue by VenyaPanou** [threefoldtech/test_feedback#230]
Error : No usable data found 
![image](https://user-images.githubusercontent.com/106578096/172806373-2cfe0ac6-1863-40af-8fb8-5a1c939f90d1.png)
TF-Chain Portal on Testnet: https://portal.test.grid.tf/
TF-Chain Portal on Devnet: https://portal.dev.grid.tf/
No.363 - TC261Transfer TFT from Stellar to Substrate
Deploying on:
Testnet,
Grid v0.1.32

**Comment by ramezsaeed** [comment]
supported flow is to scan only from the threefold connect app
