### ISSUE TITLE
TC547. When the Https connection gets enforced, trying to use ssl certificate and throws error

### ISSUE THREAD

**Issue by VenyaPanou** [threefoldtech/test_feedback#232]
I used this manual when deploing Caprover 
https://library.threefold.me/info/manual/#/manual__weblets_caprover
TC547
Deploying on:
Testnet,
Grid v0.1.32,

**Comment by ramezsaeed** [comment]
@VenyaPanou 
where is the error ?
please explain exact steps.
and where is the domain created ?

**Comment by VenyaPanou** [comment]
@ramezsaeed please try to follow the link - https://captain.apps.openly.life/

**Comment by dmitri-alleo** [comment]
When you point the domain name that you own, it works with the captain subdomain
