### ISSUE TITLE
TC325. Cant deploy ubuntu 18.04, 21.04, 21.10

### ISSUE THREAD

**Issue by VenyaPanou** [threefoldtech/test_feedback#233]
i set flist to: https://hub.grid.tf/omar0.3bot/omarelawady-ubuntu-20.04.flist
set entrypoint  /init.sh
but link dont works
![image](https://user-images.githubusercontent.com/106578096/173020940-60fad4ab-8224-4488-b2ba-6cbd6521c42a.png)
ubuntu 18.04, 21.04, 21.10
![image](https://user-images.githubusercontent.com/106578096/173021027-f7e81d1b-c156-4f62-b2f7-f50e8551a38a.png)
Deploying on:
Testnet,
Grid v0.1.32

**Comment by ramezsaeed** [comment]
Make sure we dont use un-official images.

**Comment by mohamedamer453** [comment]
[TC325](https://app.testlodge.com/a/26076/projects/40893/suites/194664?expand_section=308024#case_3375096) Was updated with the official images.

Official Ubuntu flists can be found on [Flist Hub](https://hub.grid.tf/tf-official-vms).

I was able to successfully deploy 3 vm through terraform with the mentioned versions


### 18.04

![image](https://user-images.githubusercontent.com/101194226/173236889-0d7af544-c803-4e30-ad34-6ffc2ff70adb.png)

### 20.04

![image](https://user-images.githubusercontent.com/101194226/173237162-8c372ba6-5cbf-49cd-8197-0536a9ad75fa.png)

### 22.04

![image](https://user-images.githubusercontent.com/101194226/173237477-68f21c4c-481b-4b16-b774-05f937602e11.png)

**Comment by VenyaPanou** [comment]
@mohamedamer453 thanks , but task  " can deploy ubuntu 18.04, 20.04, 21.04, 21.10 (ssh inside, and can connect) using terraform"

**Comment by dmitri-alleo** [comment]
@mohamedamer453 shall we update the task and skip the 21-release and mark it as passed?
The other 3 (18, 20 and 22) should be working, yes

**Comment by mohamedamer453** [comment]
Yes, i think the related test cases/requirements should be updated because there are no official images of the 21-release available on [Zero-OS Hub](https://hub.grid.tf/) and as @ramezsaeed mentioned before only official images should be used for testing.
