### ISSUE TITLE
TC262. Withdraw to Stellar dont work 

### ISSUE THREAD

**Issue by VenyaPanou** [threefoldtech/test_feedback#237]
TF-Chain Portal on Devnet: https://portal.dev.grid.tf/
TF-Chain Portal on Testnet: https://portal.test.grid.tf/
I added valid Stellar Target Wallet address and i saw error mess : adress not found.
![image](https://user-images.githubusercontent.com/106578096/173180453-ef1acc12-33c6-4b48-b10b-fe59bc5b4988.png)
But i can withdrawal with Transfer flow
![screenshoteasy (3)](https://user-images.githubusercontent.com/106578096/173180566-b8f50431-2bb4-4480-9fd6-73df5ae16e01.png)
 Deploying on:
Testnet,
Grid v0.1.32

**Comment by ramezsaeed** [comment]
@VenyaPanou 
Please specify the stellar address used on devnet and testnet, if it testnet address or main address?
The address used looks wrong actually.

**Comment by VenyaPanou** [comment]
@ramezsaeed I made a translation to https://portal.dev.grid.tf.
when I entered this address in the Transfer flow , the translation worked
