### ISSUE TITLE
TC387. Threefold tech/qsfs repository no exists

### ISSUE THREAD

**Issue by VenyaPanou** [threefoldtech/test_feedback#238]
Steps
1. Navigate to https://hub.docker.com/u/threefoldtech
2. Search threefoldtech/qsfs
Act resul:
![image](https://user-images.githubusercontent.com/106578096/173314159-eb5f48b7-afe2-4100-9ffb-289a6e6b0f19.png)

But if i m searching only "qsfs" 
![image](https://user-images.githubusercontent.com/106578096/173314279-d801fceb-3f2f-42f0-8cbb-50c2b742e0d8.png)
I think he data is stored under the wrong name

**Comment by ramezsaeed** [comment]
@mohamedamer453 
please validate and check the docker images is working with the flow you had tested before.

**Comment by dmitri-alleo** [comment]
Yes, confirmed, there is not QSFS image in ThreeFold repo

**Comment by mohamedamer453** [comment]
According to TC387 there should be an official qsfs image available on threefoldtech/qsfs. so we shouldn't use unofficial images. and the issue with the official images is being followed here https://github.com/threefoldtech/quantum-storage/issues/20
