### ISSUE TITLE
TC735 - TFConnect wallet - Token unlocking

### ISSUE THREAD

**Issue by dmitri-alleo** [threefoldtech/test_feedback#246]
When trying to access the documentation at https://tokenservices.threefold.io/threefoldfoundation/vesting_service/vesting_accounts

Getting this error:
![image](https://user-images.githubusercontent.com/65153287/174017746-57a2735b-74db-4251-aed3-47be8b037106.png)

And if trying to access the link from the mobile, getting the DNS_PROBE error, so doesn't open the page either

**Comment by ken-de-moor** [comment]
@rkhamis not really sure how this is related to wallet exactly. Is this the actual unlocking of tokens or is this the vesting flow? Vesting was disabled in last wallet versions and unvesting isn't implemented yet. The documentation linked is also not something we even are aware of existing. Either way unvesting and unlocking would be a monthly operational process and not really something that can be tested seperately.
