### ISSUE TITLE
Owncloud Bad Gateway

### ISSUE THREAD

**Issue by mohamedamer453** [threefoldtech/test_feedback#25]
Received Bad Gateway when accessing OwnCloud after deployment on testnet
![image](https://user-images.githubusercontent.com/101194226/157396555-43f89dc0-650e-4da7-9646-72028f7dcdcb.png)

**Comment by mohamedamer453** [comment]
after waiting around 15 mins it worked properly 
![image](https://user-images.githubusercontent.com/101194226/157403202-21a7f504-8eb0-4f5a-9e16-7e024825e141.png)

**Comment by rkhamis** [comment]
There's a message that says it takes a few minutes to be up. @mohamedamer453 please reopen if it's not clear enough

**Comment by rkhamis** [comment]
There's a message that says it takes a few minutes to be up. @mohamedamer453 please reopen if it's not clear enough
