### ISSUE TITLE
TC570 - Sending Tokens from Threefold Hub to BSC

### ISSUE THREAD

**Issue by dmitri-alleo** [threefoldtech/test_feedback#250]
Got test BNBs from the chain,
Trying to send the BSC to Kepls address, getting this error:

Portal and MetaMask
![image](https://user-images.githubusercontent.com/65153287/174790221-676dcfc9-5dd3-4f1a-aa2b-0cc36c598087.png)

Keplr on the threefold-hub-testnet
![image](https://user-images.githubusercontent.com/65153287/174790651-13990f5f-7ce9-461c-9b62-7be430a428f0.png)

**Comment by rkhamis** [comment]
@dmitri-alleo can you provide your address? seems the error says the account doesn't exist

**Comment by dmitri-alleo** [comment]
@rkhamis yes, it seems it's looking for the ERC20 address, but what I was able to get from the binance faucet were BNBs, 

The question is how to make the transactions between different accounts and chains, this part is quite unclear,
since the documentation says "send from one to another", but there is no hint how to put them there originally,
the bridge on the Testnet doesn't work to bridge from TFT to Stellar, and so the faucets for TFTs don't

Please advise

**Comment by xmonader** [comment]
@dmitri-alleo I'm not sure if understand the problem

to transfer to accounts on the hub: you go to `Send to Threefold Hub` link and put the address of the recipient (from keplr) 
to transfer to accounts on binance: you go to `Send to BSC` and put the binance address of the recipient (from metamask)

**Comment by dmitri-alleo** [comment]
@xmonader yes, but my question is how do I get some funds into the wallets initially?

**Comment by xmonader** [comment]
You can get it from BSC faucet. https://testnet.binance.org/faucet-smart
