### ISSUE TITLE
Weblets 1.4.3-RC2

### ISSUE THREAD

**Issue by dmitri-alleo** [threefoldtech/test_feedback#253]
Trying to add the accounts that were used on the testnet, 
When entering the account name (same as in the testnet and in polkadot extension) and corresponding mnemonic,
getting the error that maybe account is not activated (when trying to activate it)

![image](https://user-images.githubusercontent.com/65153287/174962590-54c15301-023b-46ef-99c7-9cca69376742.png)

The account is allowed to use any chain on the polkadot extension,

Also, managed to add the account to the portal, but when trying to fund the account in portal (Get more TFT), it throws an error that the account cannot be funded

Weblets: v1.4.3-qa2
https://play.qa.grid.tf/#/

Portal: https://portal.dev.grid.tf

**Comment by AhmedHanafy725** [comment]
@dmitri-alleo a twin needs to be created on the portal, but it should be done on https://portal.qa.grid.tf not devnet one

**Comment by dmitri-alleo** [comment]
Thank you @AhmedHanafy725 
it's working now as expected
