### ISSUE TITLE
TC583 -  Purchase TFTs with Fiat - Testnet

### ISSUE THREAD

**Issue by dmitri-alleo** [threefoldtech/test_feedback#255]
Getting an error "A Temporary Error Occured" when trying to purchase the TFTs from the Test Shop https://test.gettft.com/gettft/shop/#/buy

![image](https://user-images.githubusercontent.com/65153287/175024336-8a8319bf-1e32-42f9-97bb-34b37333c55e.png)

After some time the SSHuttle connection closes with timeout
```
sw-alleo:~ $ sshuttle -r root@188.206.122.151 0.0.0.0/0 --dns -v
Starting sshuttle proxy.
firewall manager: Starting firewall with Python version 3.8.10
firewall manager: ready method name nat.
IPv6 enabled: False
UDP enabled: False
DNS enabled: True
User enabled: False
TCP redirector listening on ('127.0.0.1', 12300).
DNS listening on ('127.0.0.1', 12299).
Starting client with Python version 3.8.10
c : connecting to server...
ssh: connect to host 188.206.122.151 port 22: Connection timed out
c : fatal: failed to establish ssh session (2)
```

Env: Testnet
Whitelisted VM IP: 188.206.122.151

**Comment by xmonader** [comment]
@sameh-farouk can you please check the error logs for this

**Comment by sameh-farouk** [comment]
I don't have an access. @hossnys can you help?

**Comment by sameh-farouk** [comment]
@hossnys nvm I didn't notice that dmitri closed the issue already
