### ISSUE TITLE
TC757 - Delete Kubernetes Workers

### ISSUE THREAD

**Issue by VenyaPanou** [threefoldtech/test_feedback#256]
error on the front: 
![image](https://user-images.githubusercontent.com/106578096/175028617-e3292acc-e4a0-4bd2-a0d8-38001554e022.png)
but after executing kubectl get nodes the status of the worker is changed to **NotReady**
![image](https://user-images.githubusercontent.com/106578096/175029078-97dd6559-f62a-42ab-a847-8b1d62a903c2.png)

Weblets: v1.4.3-qa2
https://play.qa.grid.tf/#/
Portal: https://portal.qa.grid.tf/

**Comment by mohamedamer453** [comment]
Tested on Weblets v1.4.3-qa3

I was able to reproduce this issue a couple of times with 2 different setups and each time after i close the modal box and refresh the page i find that the worker was actually deleted and when i execute `kubectl get nodes` the status of the worker is `NotReady`.

### First setup

- Deployed a cluster with a master and no workers.
- Added a worker to the cluster
- Tried to delete the worker
- Failed with the mentioned error `Failed to remove worker`
- However the worker was actually removed when i refreshed the page.

### Second setup

- Deployed a cluster with a master and one worker.
- Tried to delete the worker
- Failed with the mentioned error `Failed to remove worker`
- However the worker was actually removed when i refreshed the page.

![image](https://user-images.githubusercontent.com/101194226/175312030-7ff8402e-945b-4f2b-aff3-6e9cea523fa6.png)

**Comment by xmonader** [comment]
will track in https://github.com/threefoldtech/tfgrid-sdk-ts/issues/140
