### ISSUE TITLE
Disk name not changed in the Mount Point input 

### ISSUE THREAD

**Issue by VenyaPanou** [threefoldtech/test_feedback#257]
![screenshoteasy (5)](https://user-images.githubusercontent.com/106578096/175228304-305e404e-beca-43b4-8b99-b4c31079d079.png)
mounts": [
        {
            "**name": "AAAAAAAAAA",
            "mountPoint": "/mnt/92fa6bf4",**
            "size": 53687091200,
            "state": "ok",
            "message": ""

TC665
Weblets: v1.4.3-qa3
https://play.qa.grid.tf/#/
Portal: https://portal.qa.grid.tf/

**Comment by dmitri-alleo** [comment]
If I remember correctly the functionality was updated not to update the disk name after all, so in this case the test case can be removed from the test suit
