### ISSUE TITLE
TC662 - Show full billing rate info instead of '< 1 TFT'

### ISSUE THREAD

**Issue by VenyaPanou** [threefoldtech/test_feedback#259]
Billing rate displayed not correctly ( Owncloud )

Ex.res:The amount shown should be less than 1 TFT, but the number should show the exact amount charged, for example 0.0521 TFT

Act.res: 
![image](https://user-images.githubusercontent.com/106578096/175238906-792019ba-7cfd-40e9-90a3-e58ff0dcb48b.png)
Billing rate: 3.3947387 TFT/hour for Owncloud
Billing rate: 2.7493524 TFT/hour for VM

TC662
Weblets: v1.4.3-qa3
https://play.qa.grid.tf/#/
Portal: https://portal.qa.grid.tf/

**Comment by xmonader** [comment]
Actually this issue isn't correct

the test case is about showing the exact amount instead of the word `Less than 1TFT `, which is the case.

If you have any doubts about the pricing of owncloud or VMs please open another issue
