### ISSUE TITLE
Uhuru sign-in from mobile doesn't appear to work

### ISSUE THREAD

**Issue by Miket188** [threefoldtech/test_feedback#263]
I clicked on the link in the tweet and entered my ThreeFold Connect name and it went to a blankscreen.

Worked fine on my laptop.

3bot name was correct (trout2).

Using iPhone 12, Chrome.

**Comment by ken-de-moor** [comment]
Only chromium is supported for now. IPhone isn't expected to work. Mobile is also v1.4, support for mobile is extremely experimental in v1.3

**Comment by Miket188** [comment]
I see

**Comment by ken-de-moor** [comment]
Closing this in favour of the feature request on Uhuru, known issue and not expected yet for 1.3

https://github.com/threefoldtech/twin_aydo/issues/544
