### ISSUE TITLE
TFConnect: Message (Memo Text) Field

### ISSUE THREAD

**Issue by mohamedamer453** [threefoldtech/test_feedback#267]
In the `Send Coins` page there is a field called `Message` this field is supposed to accept the twin id of the account you are sending the coins for, but there is no indication what the user should enter in this field.

![image](https://user-images.githubusercontent.com/101194226/183293653-3f727d41-4d7c-47da-8d12-fc953dc9d661.png)

there should be a placeholder in the field that says `Please enter your twin id` or a tooltip that mentions where this twin id can be found and what is the correct format to write it in `twin_<twin id>`.

and if this field is only used for the twin id it should be renamed and there should be validation for this field that only accepts the following format `twin_<twin id>`.

**Comment by ramezsaeed** [comment]
After investigation found that this is the Bridge address not normal user wallet address,
so with bridge address twin_ID is needed to verify the user receptor.
