### ISSUE TITLE
Cannot Deploy Public Addresses on Devnet 

### ISSUE THREAD

**Issue by Parkers145** [threefoldtech/test_feedback#272]
Greetings I set up a node on Dev net and it unable to deploy a vm with public addresses, my mainnet nodes are able to though. 

attempting to deploy on farm 59 node 45 I Get 
![image](https://user-images.githubusercontent.com/44621168/183688457-804961b8-af0f-4f88-895f-922783d8e139.png)

I initially suspected this was a public config issue, But, I was able to validate the nodes public ipv4 and ipv6 are both pingable. 
![image](https://user-images.githubusercontent.com/44621168/183688678-f6340d5a-8d71-43ce-818a-d4c89771bb49.png)
![image](https://user-images.githubusercontent.com/44621168/183688719-146b05ba-3b22-4e39-9fc0-4a98fc89be7b.png)
![image](https://user-images.githubusercontent.com/44621168/183688753-2281f1d5-65ea-42f0-8635-7dd2d8b536c8.png)

This is what is showing on the node, 

![IMG-6009](https://user-images.githubusercontent.com/44621168/183689680-5e9151d4-36ac-4e80-b121-ecbfcb77bbdd.jpg)
![IMG-6008](https://user-images.githubusercontent.com/44621168/183689686-9d3d2302-f6b7-4faa-991b-7aa4e3080d96.jpg)

**Comment by coesensbert** [comment]
Hi @Parkers145 
What DNS IP is your local DHCP sending on the DMZ nic (first one) of your ZOS node?

**Comment by Parkers145** [comment]
I believe it is sending its own gateway address as the dns. I’ll be home in about an hour to check

there has been a vm running since last night showing an ipv4 reservation that’s not one of mine so I added a few more ips 

the active vm is from contact 5888, I think it’s something of azmy’s?

**Comment by Parkers145** [comment]
![74E09EE0-F98B-4BF5-97F2-702E7DECD419](https://user-images.githubusercontent.com/44621168/183897186-e2f64130-f476-4a66-ad35-7df09077369d.png)
![BF2F22C3-023A-4756-8D9A-3496EC974779](https://user-images.githubusercontent.com/44621168/183897192-74eeb2f9-dd21-4b92-bd54-ebc53bcf9a4f.jpeg)

updates: 

From what I can tell dns request go to gateway then to the dns listed above whitch is an Att dns server. Have had some changes to the node console aswell

**Comment by Parkers145** [comment]
![5E454DAB-DD20-44AF-A79C-5E88C57D866D](https://user-images.githubusercontent.com/44621168/183907290-5dec2ed9-970b-4eb2-9f6c-3aeda6d4e5fa.jpeg)

new behavior

**Comment by Parkers145** [comment]
Issue update, 

I migrated one of my production nodes over to devnet to verify this wasnt device specific. Its active as node 46, farm 59 but isnt showing in the dashboard and cant deploy anything. 

Its public ips are 
162.205.240.144 
and 
2600:1700:c1e0:1150:f4d0:96ff:fec9:ecca/64

both ping externally. I noted that its DMZ nic only has a link local ipv6 address. 

this nodes has 5gig up and down in place and is the only thing on that line so it should be a great testing environment once it shows up.

**Comment by coesensbert** [comment]
Hmz, if the DNS is a public ip it's not what I suspected.

Also checked some console's of our devnet ZOS nodes and they don't have these error's.

There where some issues with the graphql on devnet, maybe it's related.

**Comment by Parkers145** [comment]
Both of these problems seem to have resolved currently, deployments are working on 45 and 46 is showing in explorer. 

I saw a lot of errors related to metadata not found and query response time limit violations. Definitely could be graphql related

**Comment by ramezsaeed** [comment]
As all resolved, will close this for now.
and please feel free to re-open if reproduced again
