### ISSUE TITLE
threefold documentation 

### ISSUE THREAD

**Issue by doaasaber** [threefoldtech/test_feedback#277]
- In getting started some titles of pages Appear as URLs 

![image](https://user-images.githubusercontent.com/54359761/186112548-13143a44-28d7-4952-b285-3b0161e6458a.png)

- In activate twin needs to mention steps and website link to get the ip 

![image](https://user-images.githubusercontent.com/54359761/186113465-d0fe662e-6170-4432-ab3b-f992968a4d11.png)

- for generating the ssh key no clear steps or links are mentioned 

- There’s a wablet called node pilot in the document but doesn't exist on the website

- In FAQ a lot of questions redirect to the not found page.

**Comment by ramezsaeed** [comment]
moved to: https://github.com/threefoldfoundation/info_manual3/issues/91
