### ISSUE TITLE
Presearch nodes, connection issues on both main- and testnet

### ISSUE THREAD

**Issue by jesmoilija** [threefoldtech/test_feedback#281]
portal.grid.tf dashboard websie is not working. Just saying "connecting to Polkadot". 

play.test.grid.tf Presearch node does not work anymore. Presearch's own dashboard says it is disconnected, maybe a temporary problem? If node keys created via Threefold interface, the staked PRE tokens has no usage. Would be nice to have some kind of tool to export the created private and public keys directly from Threefold's Presearch tab, since there is no any visibility what is happening on the server. Or any possibility to use Linux commands to restore the private keys. That would also then make it possible to move the existing node from testnet to mainnet without losing the node keys which are staked (presearch allow you to use lower amount of PRE for older nodes).

**Comment by coesensbert** [comment]
portal.grid.tf -> the portal is deprecated and points now to the dashboard. If it's not loading try clearing your cache or use a different browser. Or you can go directly to https://dashboard.grid.tf/

**Comment by Omarabdul3ziz** [comment]
the docs for migration should help with that. you can copy your keys from the old node and deploy another node with these keys from the restore tab on the playground. [check the docs](https://library.threefold.me/info/manual/#/manual__weblets_presearch?id=now-what-if-you-already-have-a-presearch-node-deployed-somewhere-and-would-like-to-migrate-to-threefold)

**Comment by mohamedamer453** [comment]
The issues related to presearch were fixed and verified in https://github.com/threefoldtech/tfgrid-sdk-ts/issues/130, and as mentioned in the comment above 

> the docs for migration should help with that. you can copy your keys from the old node and deploy another node with these keys from the restore tab on the playground. [check the docs](https://library.threefold.me/info/manual/#/manual__weblets_presearch?id=now-what-if-you-already-have-a-presearch-node-deployed-somewhere-and-would-like-to-migrate-to-threefold)

you can follow the migration docs to copy your node keys from the old node and deploy a new one using the restore key and this will be deployed with the updated and fixed presearch flist.
