### ISSUE TITLE
Planetary Network Option is not available for the iOS version of Threefold Connect

### ISSUE THREAD

**Issue by mohamedamer453** [threefoldtech/test_feedback#284]
According to [REQ172](https://app.testlodge.com/a/26076/projects/40893/requirements/38034#item_207987) & [TC386](https://app.testlodge.com/a/26076/projects/40893/suites/195345?expand_section=309756#case_3391384) Threefold connect on iOS should have `Planetary Network` option like the one available in the android version. However on the latest iOS version this option is not available.

### iOS Version

![image](https://user-images.githubusercontent.com/101194226/188676319-9f0f0dc6-b865-4771-98a5-dda2f4a1b46d.png)

![image](https://user-images.githubusercontent.com/101194226/188676399-ba0a3f83-d7a3-45b1-b10e-fa68701b9c97.png)

### Android Version

![image](https://user-images.githubusercontent.com/101194226/188676226-4b7bbbe0-797a-4de3-9af9-f740a8b74997.png)

![image](https://user-images.githubusercontent.com/101194226/188677361-fdc26b45-18ee-4e44-8327-c8929f0e25b7.png)

**Comment by lennertdefauw** [comment]
@mohamedamer453  no clue why this was turned off for asharby, should be fixed now.

**Comment by A-Harby** [comment]
`Planetary Network` option is now displayed in the menu.
However it crashes when I attempt to connect to it, so I kept trying till it asked me to allow editing vpn configuration and it works now. 

![image](https://user-images.githubusercontent.com/109473873/191212600-75cf32de-bb46-414c-b509-363d7a569ab1.png)
