### ISSUE TITLE
gettft.com is displaying incorrect stats

### ISSUE THREAD

**Issue by mohamedamer453** [threefoldtech/test_feedback#285]
The landing page of [Get TFT](https://gettft.com/gettft/) is displaying incorrect stats and as seen in the screenshot below the stats displayed doesn't match the stats in https://stats.grid.tf/

![image](https://user-images.githubusercontent.com/101194226/188845560-66e961d9-b78d-46ea-a6c2-154e74a6c7f4.png)

Also the `See Full Stats` button redirects the users to https://explorer.threefold.io/all while it should redirect to https://stats.grid.tf/

**Comment by xmonader** [comment]
it was a snapshot at that time.
