### ISSUE TITLE
Deleted vps 6h ago but contract not deleted

### ISSUE THREAD

**Issue by s-areal** [threefoldtech/test_feedback#287]
Deleted a VPS and deployed 2 new ones 6 hours ago. The hourly rate multiplied by the number of hours x 2 VPS shows up a huge diference. Found out now that even deleting the VPS the contract is still running.
I am beeing charged 7 times the price that shows up on hourly rate!!!

![Captura de ecrã 2022-09-10, às 20 03 15](https://user-images.githubusercontent.com/49781569/189498104-e1ebea68-fde7-4a6c-ba1d-7e77ac26d978.png)

![Captura de ecrã 2022-09-10, às 20 03 33](https://user-images.githubusercontent.com/49781569/189498115-2401b74d-291a-458d-985d-c5982bd1e3ab.png)

**Comment by s-areal** [comment]
The image above is the contracts list : 3 contracts
the image bellow show the current VPS running

**Comment by rkhamis** [comment]
since there's no way to trace this without the contract details, we opened an issue https://github.com/threefoldtech/grid_weblets/issues/1004. should make it easier to find out what went wrong

**Comment by mohamedamer453** [comment]
A new feature was added in https://github.com/threefoldtech/grid_weblets/issues/1004 where the user is now able to view contract details from the contracts tab in the grid weblets.

***note: this feature is not available yet on test/mainnet and it will be available with the `3.8` release.
