### ISSUE TITLE
Time sync issues

### ISSUE THREAD

**Issue by Parkers145** [threefoldtech/test_feedback#288]
I have been regularly having difficulty with my nodes having ssl errors and time outs during network functions that Is a problem affecting my entire network not just the nodes. 

I found the problem to be that my ISP blocks all port 123 traffic. Yay. So, I have tested a solution on my local network that I think can be beneficial across the grid because of how important time is. 

Within my network I tested a server running planetary with a local public peer list and a time server then peering to it from client devices over planetary 

but I worry that this issue could be affecting some of my nodes, 

as a proposed solution, I think my local solution could be replicated on grid by the nodes pointing to a time server on planetary, or each gateway being a planetary time server.

as an interesting feature this could open up the planetary client to have a function that creates a time server at 127.0.0.1:123 that is linked up to an a tunneled and encrypted network of time servers over random ports opening up a use case where every user of my isps service could install planetary then be able to point local devices to that time server locally avoiding the problem of the blocked port that’s likely to replicate. 

While a small feature it will attract a specific subset of users we need, home labbers already looking for solutions to their isps censorship.

**Comment by muhamadazmy** [comment]
Thanks for reporting this, and the work you have put into it.
- It's so weird that your ISP is blocking the NTP protocol port. 
- The thing is we use already a distributed ntp servers from `https://www.ntppool.org/en/` to sync node time for exactly those reasons. 
- I would love to keep using a public "trusted" one because if someone hosted a misconfigured server on the planetary network it might affect the entire grid.

**Comment by Parkers145** [comment]
I had noticed the node themselves were getting time. This problem hid pretty well until I put in a hpe managed switch that could get a time sync, the nightmares were endless

**Comment by ramezsaeed** [comment]
it's a local problem with isp.
will close it for now.
