### ISSUE TITLE
Make environment variables available in flist container

### ISSUE THREAD

**Issue by lennertdefauw** [threefoldtech/test_feedback#289]
Currently deploying an flist with the grid3 typescript client. 

Giving environment variables to the VM

![image](https://user-images.githubusercontent.com/43674202/190602154-6066cb35-4437-4936-ad91-5331bf3495ee.png)

Logging in with ssh to the public IP, getting the environement variables returns me to

![image](https://user-images.githubusercontent.com/43674202/190603866-0799213d-f45f-4be4-b5ee-a7ea44346fa9.png)

No pregiven env vars were found. Environement variables are availble in your entrypoint, but they should be available anywhere. Trying to EXPORT USER_ID = "lennertapp2" inside my entrypoint script didnt work either.

**Comment by coesensbert** [comment]
Can't help with that but I wonder what flist did you use?

**Comment by lennertdefauw** [comment]
I am using the following flist: https://hub.grid.tf/lennertapp2.3bot/threefoldjimber-ssh-latest.flist

**Comment by lennertdefauw** [comment]
This is needed to have a generic flist where we can just pass through environment variables for a Vue3 NodeJS application

**Comment by coesensbert** [comment]
Is this a full vm or container based flist?

**Comment by lennertdefauw** [comment]
This is the Dockerfile:


```
FROM ubuntu:20.04
RUN echo deb http://be.archive.ubuntu.com/ubuntu/ focal main restricted universe multiverse >> /etc/apt/sources.list
RUN apt-get update && DEBIAN_FRONTEND=noninteractive TZ=Europe/Belgium apt-get install -y openssh-client openssh-server && rm -rf /var/lib/apt/lists/*
COPY init.sh /init.sh
RUN chmod +x /init.sh
ENTRYPOINT ["/init.sh"]
```
with init.sh:

```
#!/bin/bash

export TEST='TEST'
export USER_ID=$USER_ID

mkdir -p ~/.ssh
mkdir -p /var/run/sshd
echo $SSH_KEY >> ~/.ssh/authorized_keys
chmod 600 ~/.ssh/authorized_keys
exec /usr/sbin/sshd -D
```

**Comment by xmonader** [comment]
the env vars are available to process 1
e.g 

![image](https://user-images.githubusercontent.com/64129/190852494-6ed60415-5bad-45ad-9b28-69e697b63f9c.png)


![image](https://user-images.githubusercontent.com/64129/190852472-f74304ff-1e53-4e57-9d01-4197be91a404.png)
