### ISSUE TITLE
Npm package grid3_client 1.3.4 doesnt work on mainnet

### ISSUE THREAD

**Issue by lennertdefauw** [threefoldtech/test_feedback#290]
In README.md, grid3_client 1.3.4 should be compatible with current mainnet, but isn't. After searching out,  tfgrid-api-client has a wrong version number (1.16) which causes this error

Error: Error: Failed to create contract on node: 17 due to Error: Extrinsic smartContractModule.createNodeContract expects 4 arguments, got 5.

solution: manual set a lower tfgrid-api-client to 1.12 by doing npm add tfgrid-api-client@1.12.1

**Comment by xmonader** [comment]
have to double check, because the production of mainnet of the playground is using 1.3.4 already without problems https://github.com/threefoldtech/grid_weblets/blob/ac7551eec59adcf1bd45693a29760cfaae4c53a2/package.json#L63  could it be another caching problem like the one you faced couple days ago?

**Comment by ramezsaeed** [comment]
Will be solved in the new mainnet upgrade

**Comment by AhmedHanafy725** [comment]
mainnet is upgraded. And the grid client now gets the correct version of the `tfgrid-api-client`
