### ISSUE TITLE
Unable to add DNS to my public IP

### ISSUE THREAD

**Issue by lennertdefauw** [threefoldtech/test_feedback#291]
Got a VM running on public IP http://185.69.166.145:80 with default nginx installed and is available on port 80:

![image](https://user-images.githubusercontent.com/43674202/190636566-b1cac74f-b711-4ace-bad6-6ac46c57520d.png)

Want to have userfriendly accessibility, so want to provide DNS.

Using grid3_client in typescript with freefarm (farmID: 1) where gateways are correctly configured:

(based on docs in manual) https://library.threefold.me/info/manual/#/manual3_iac/grid3_javascript/manual__grid3_javascript_vm_gateways
```
    await gridClient.connect();

    const gatewayQueryOptions: FilterOptions = {
        gateway: true,
        farmId: 1,
    };

    const gw = new GatewayNameModel();
    gw.name = "lennertapp2";

    gw.node_id = +(await gridClient.capacity.filterNodes(gatewayQueryOptions))[0].nodeId;
    gw.tls_passthrough = false;

    gw.backends = ["http://185.69.166.145:80"];

    // deploy
    const res = await gridClient.gateway.deploy_name(gw);
    console.log(res);

    // get the deployment
    const l = await gridClient.gateway.getObj(gw.name);
    console.log(l);


    await gridClient.disconnect();
```

got this as result

```
[
  {
    version: 0,
    contractId: 6617,
    name: 'lennertapp2',
    created: 1663326789,
    status: 'ok',
    message: '',
    type: 'gateway-name-proxy',
    domain: 'lennertapp2.gent01.grid.tf',
    tls_passthrough: false,
    backends: [ 'http://185.69.166.145:80' ],
    metadata: '',
    description: ''
  }
]
```

so I would expect lennertapp2.gent01.grid.tf now would be available and redirects to http://185.69.166.145:80

but this is the result

![image](https://user-images.githubusercontent.com/43674202/190636895-25810d57-7d44-44f6-9b9b-39e397fb4477.png)

Am I doing something wrong?

**Comment by coesensbert** [comment]
Looks correct.

It works now! Found a small typo in the CNAME of the public domain config

**Comment by lennertdefauw** [comment]
Nice! Thank you :)
