### ISSUE TITLE
Network modifications affect vms grid reporting 

### ISSUE THREAD

**Issue by Parkers145** [threefoldtech/test_feedback#292]
kind of a long story but i was able to prevent a deployed vm from billing properly.

to do this, i was working in a ubuntu 22.04vm running cockpit, 

in order to attempt to remediate a application issue i switched the renderer in netplan to "renderer: NetworkManager"
then ran 

systemctl disable systemd-networkd  && Systemctl enable NetworkManager
Netplan apply

this left the public ip address interface functional and the vm functional but all billing stopped. 

while your checking this out check, there is a full ubuntu VM deployed running a graphical web management interface called cockpit on the grid at 162.205.240.133:9090, Scott has a login if your want to check it out.

**Comment by xmonader** [comment]
@delandtj please take a look

**Comment by Parkers145** [comment]
i believe i have the fixed the issue 

![image](https://user-images.githubusercontent.com/44621168/190918069-338ac99d-6a0f-49bf-b2ba-c3d5a1d9635a.png)


it seems that when i switched into network-manager it didnt like the gateway4 address in the ens4 config, i switched this to routes and the bridges between all of the networks seem to be functioning properly now. 

the changes to the planetary interface are unrelated.

**Comment by Parkers145** [comment]
I think this was an isolated incident due to other testing as the deployments are now functioning properly, 

couple notes on closing in recreating this the vm didn’t survive reboots so it’s temporary. 

While I was able to get the vm working again, it was because i had actually broken the overlay, so it does self correct on reboot, but a vm can be removed from the overlay and operate on the public IP without reporting uptime temporarily. 

Interesting facts the mru, cru, and sru reservation disappears from the nodes screen, the ipv4 reservation reports accurately. 

Could there be a check that if a ipv4 is contracted, there must also be matching reservations to catch this live?

**Comment by delandtj** [comment]
O_o
billing stopped ? can you elaborate on how you think billing stopped ?
We suppose you mean that 'all billing' refers to the number of NU (network units)? 
The node's screen is, err... due for a little love, we'll make it more accurate retrieving correct info from the grid. Today that thingie is a bit 'best effort'.
Thanks

**Comment by Parkers145** [comment]
basically, once I broke the interface that carries the 10.0.0 Ip traffic, the vm disappeared from existence but remained functional and accessible on the public ip. but when i would look in play i had no vms running, and nothing billing, even though i was still logged into it. 
 
so i was still using a vm my play interface wasnt deducting for. i was experimenting with port forwarding, and made it so that outbound traffic on the overlay interface was actually going somewhere else because i choose the wrong interface in my command (messed up the static routes). when i did that, the deployment stayed up, but disappeared from play.

**Comment by ramezsaeed** [comment]
@DylanVerstraete @AhmedHanafy725 
please check ..

**Comment by DylanVerstraete** [comment]
Is there a twin id or contract id that we can check?

**Comment by muhamadazmy** [comment]
Nothing billing is a very big word actually because billing information comes from multiple places:
- Public IP reservation happens completely on the chain, you pay for the IP even if you are not using it
- CU, SU, MU are reported "on deploying" and is remembered by the chain. So this is a constant billing to your VM that is not related to network, instead only takes the size of your VM into account (number cpu, memory and disk)
- Finally NU only accounts for traffic that goes over your PUBLIC interface. so if all your traffic (say downloading from the internet) is using the private network (overlay network) no NU are counted. But all public traffic (say user connecting to your VM over the public) is.

So you need to be specific about what exactly is not billed:

**Comment by Parkers145** [comment]
> Nothing billing is a very big word actually because billing information comes from multiple places:
> 
> - Public IP reservation happens completely on the chain, you pay for the IP even if you are not using it
> 
> - CU, SU, MU are reported "on deploying" and is remembered by the chain. So this is a constant billing to your VM that is not related to network, instead only takes the size of your VM into account (number cpu, memory and disk)
> 
> - Finally NU only accounts for traffic that goes over your PUBLIC interface. so if all your traffic (say downloading from the internet) is using the private network (overlay network) no NU are counted. But all public traffic (say user connecting to your VM over the public) is.
> 
> 
> 
> So you need to be specific about what exactly is not billed:

I will try to replicate it so you can assess a live specimen, my twins balance didn't change for 24+ hours. I don't know how to turn that into usable information in regards to why though
