### ISSUE TITLE
/ cant be mount 

### ISSUE THREAD

**Issue by Parkers145** [threefoldtech/test_feedback#293]
![image](https://user-images.githubusercontent.com/44621168/190934807-9d2a905e-9baf-4795-a76e-94d1dcd30e99.png)

trying to deploy and full vm image that isnt the 22.04 official image i get this, can someone tell me how to make my .flist work!? i have searched every corner of the forums and google and cannot find a shred of documentation on how i need to image my working deployment and package it so its deployable!

**Comment by coesensbert** [comment]
This is the documentation I know of, regarding images for the grid: https://github.com/threefoldtech/zos/blob/main/docs/manual/zmachine/zmachine.md#creating-vm-image

I'll do my best to write a guide this week on how to manipulate these cloud images for your needs.

**Comment by Parkers145** [comment]
your the man that gets me moving

**Comment by coesensbert** [comment]
Basic guide to manipulate cloud images: https://forum.threefold.io/t/manipulating-cloud-images-for-the-grid/3380
