### ISSUE TITLE
Play Profiles disappearing 

### ISSUE THREAD

**Issue by Parkers145** [threefoldtech/test_feedback#294]
over the past two days i have had to recreate my play profiles on the Testnet and Devnet multiple times, It seems that every time I clear my cache all of my profiles are gone and have to be recovered with seed phrases as it will just say incorrect password. should my profile, password and RSA not be persistent?

**Comment by rkhamis** [comment]
@Parkers145 This should never happen. you only cleared your cache? it shouldn't be affected by that. did you by any chance clear your local storage?

**Comment by Parkers145** [comment]
It seemed sporadic over a period of about 2 days that randomly though out the day my password seemed to stop working, then I’d recreate the profile and all my stuff was still there

**Comment by AhmedHanafy725** [comment]
can you please provide steps for it cause I can't really reproduce it?

**Comment by Parkers145** [comment]
I attempted to reproduce it myself, and I was unable to aswell. It hasn’t happened again since maybe 24 hours after my report

**Comment by ramezsaeed** [comment]
ok will close.
and please re-open if it happen again.

**Comment by Parkers145** [comment]
my test net profile has dissapeared again and RObertL is reporting the same
