### ISSUE TITLE
public ip interface deployment missing name server

### ISSUE THREAD

**Issue by Parkers145** [threefoldtech/test_feedback#295]
I've noticed that my public ip address interfaces do not deploy with a name server set, this prevents vms running within the deployment from resolving dns names, example below 
![image](https://user-images.githubusercontent.com/44621168/192123934-62185f44-4a78-439d-8016-c25b52e0a866.png)

**Comment by xmonader** [comment]
is it actually true that you can't resolve DNS names or that's an assumption?

@coesensbert @delandtj any idea?

**Comment by Parkers145** [comment]
> is it actually true that you can't resolve DNS names or that's an assumption?
> 
> 
> 
> @coesensbert @delandtj any idea?

I'm a little confused by your question, yes I actually found the reported problem and was able to fix it by adding a dns server to the interface . If it hadn't been weeks since I reported it I would of gladly shared access to the deployment and been able to provide you with any documentation you needed, but none of the deployments involved here exists anymore. 

If you want to replicate, deploy a cockpit image, change the virtual network that supports the vms to being a part of the public interface instead of being fed by the overlay address and run an apt update in any of the vms, it will fail to resolve as reported.

**Comment by ramezsaeed** [comment]
@sabrinasadik 
please we need one of the ops team to try this.

**Comment by Parkers145** [comment]
I’m working on getting some new network gear integrated this weekend, But I can deploy a vm a replicate this in a video one I un break things

**Comment by muhamadazmy** [comment]
Was there any modifications to the VM network setup before this issue happens? By default all VMs get dns configured by default to 8.8.8.8 and 1.1.1.1 so I am not sure why suddenly this happens with your workload.

I will gladly give it a try. This is just a normal VM (what image?) with a private network + public Ip address? right ?

**Comment by Parkers145** [comment]
So from what I could tell the Google dns was set on the first interface that was the wire gaurd interface and that is where the default vm network sets up in the cockpit images. 

I had wanted to reach a a second vm that was running inside the deployment (desktop environment) so I had moved the vm network to behind the public interface, whitch didn't have any name servers set.

I have actually started doing things a different way in the image that makes this irrelevant now and am using private ips on the vms inside the deployment and port forwarding for better control so this isn't super relevant as a problem for me anymore

**Comment by delandtj** [comment]
@Parkers145 ,
can you elaborate a bit further on :
  - what you want to obtain
  - what your config is now
 I' sure we can help you out, but now everything gets more and more confusing.
 Either way, you have a usecase, so we want to understand it fully. Might be important.
Keep up the good work, testers and pushers are oh-so welcome

**Comment by Parkers145** [comment]
My end goal was to be able to deploy these images more setup with their vm network getting access over the public interface instead of the overlay. but, I also just found out that networkmanager, which these images use and the grid aren't compatible and these images cant survive reboots of the host node so its not relevant now. the issue can be closed. 

https://forum.threefold.io/t/cockpit-managed-vm-flist-release/3398/5

**Comment by scottyeager** [comment]
Zos provides DNS configuration to one interface. This is a valid and not unusual configuration for systems with multiple interfaces.

Now if you're going to use a VM to host other VMs, I think it's normal that you would need to be conscious about where the DNS configuration for the sub VMs is being sourced and maybe do some configuration to ensure they can reach DNS.

I'm not convinced there's any good reason to change how Zos configures VMs, but the options would be:

1. Copy the DNS config to each interface
2. Apply DNS config as global. Looks like this isn't possible with the v2 cloud-init/netplan format we're currently using, but was possible in v1 or can be achieved otherwise (setting `DNS=` in `/etc/systemd/resolved.conf`)

**Comment by Parkers145** [comment]
> Zos provides DNS configuration to one interface. This is a valid and not unusual configuration for systems with multiple interfaces.
> 
> Now if you're going to use a VM to host other VMs, I think it's normal that you would need to be conscious about where the DNS configuration for the sub VMs is being sourced and maybe do some configuration to ensure they can reach DNS.
> 
> I'm not convinced there's any good reason to change how Zos configures VMs, but the options would be:
> 
> 1. Copy the DNS config to each interface
> 2. Apply DNS config as global. Looks like this isn't possible with the v2 cloud-init/netplan format we're currently using, but was possible in v1 or  can be achieved otherwise (setting `DNS=` in `/etc/systemd/resolved.conf`)


See here, 
https://github.com/threefoldtech/zos/issues/1823

It seems cockpit is going to be dead in the water unless there is an update for a version that doesn’t use NM.
