### ISSUE TITLE
Node reporting down with active workload

### ISSUE THREAD

**Issue by Parkers145** [threefoldtech/test_feedback#296]
Currently node 3049 one of my main net nodes, is reporting as down for nearly two words even though the 24/7 monitor I have hooked up says it has a workload and cpu usage.

the uptime kernel is panicked, I honestly can’t tell if the workload is actually up or not, it has a public IP so based on what I’ve seen working with cockpit it’s probably running  with no billing. 

I left it up so you can investigate, every single indicator on the node claims all is well. It’s the same kernel panic from this report, 

https://github.com/threefoldtech/zos/issues/1791

None of the other 4 nodes have gone down. We’ll post pics in the am

**Comment by Parkers145** [comment]
![E8B3CEEA-29BE-498E-85F6-99772F2F3D48](https://user-images.githubusercontent.com/44621168/192168548-f10d9ca3-e99e-4f02-9b21-107020dbf27f.jpeg)

interesting photo of the state seems the failure is isolated to the uptime reporting. 

The specimen is a dl360g8, running a bios image, upon investigation these firmware updates were due 
![785478D7-5476-48CF-8564-01BF1B75F973](https://user-images.githubusercontent.com/44621168/192168637-009f818a-7dc7-40d3-a4f5-b49513035801.jpeg)

notably the network card is a dual sfp+ 10g nic. Attached to a flex fabric 5700, 

couple known issues with my setup, dhcp issues seem to be common, the only solution I’ve found is setting interfaces to portfast/edged. I’ve help a few other farmers resolve a failure to boot issue where it fails the dhcp just before the bridges by making these changes. 

Could this also be related to the udhcp -> dhcpd change it appears my server was suggesting rolling back my network firmware to a older Linux version.

**Comment by Parkers145** [comment]
![494B5B94-F838-4DC6-97FB-4740E480A035](https://user-images.githubusercontent.com/44621168/192209440-b269173c-997a-4f72-9cb4-c3e31d36a0cf.jpeg)
![1EF8B3E3-4020-4BD6-90D4-39CE233CF00B](https://user-images.githubusercontent.com/44621168/192209446-ba41bc56-36d3-459f-88a1-1d1403e2c04b.jpeg)

the namespace issue did resolve after a good wait. Public configuration details for thoroughness.

**Comment by scottyeager** [comment]
I documented the uptime panic here: https://github.com/threefoldtech/zos/issues/1803

Node is indeed up and responds to pings in my case. It's just the uptime reporting that's not working.

**Comment by Parkers145** [comment]
Sigh, it’s back in it’s panicked state for the passed two days

**Comment by Parkers145** [comment]
![228D6D8E-C809-4023-A2C9-8FE258D47E56](https://user-images.githubusercontent.com/44621168/194730468-6e7aeb9b-22fb-4182-89e8-6193f7babaeb.jpeg)

most recent panic, 219 on testnet is the exact same server, not having this problem, 2914 is another hp on main net, do you guys have any suggestions on troubleshooting this?

**Comment by rkhamis** [comment]
@Parkers145 there was a fix pushed to mainnet on Thursday. Can you recheck the node now?

**Comment by Parkers145** [comment]
have not seen the behavior since. :)

**Comment by xmonader** [comment]
Please reopen if happens again
