### ISSUE TITLE
User is getting errors while trying to deploy with terraform

### ISSUE THREAD

**Issue by sabrinasadik** [threefoldtech/test_feedback#300]
User deployed yesterday without issues. Today getting:

Error: failed to deploy deployments: error waiting deployment: couldn't get twin public key: error connecting to substrate at 'wss://tfchain.grid.tf/ws': websocket: bad handshake (HTTP status 502 Bad Gateway); failed to revert deployments: failed to delete deployment: failed to cancel contract: failed to submit extrinsic: Priority is too low: (302980000 vs 302300000); try again,

After retry:

Error: couldn't get substrate client: error connecting to substrate at 'wss://tfchain.grid.tf/ws': websocket: bad handshake (HTTP status 502 Bad Gateway)

**Comment by coesensbert** [comment]
could reproduce, happened during mainnet upgrade.

Fixed now, can you ask the user to try again?

**Comment by sabrinasadik** [comment]
User says he found the issue  terraform parameter -parallelism=1, caused the issue, take this out and it works.

I closed tab , deleted temporary web data, closed and opened chrome + reboot. Nothing helped, installed firefox all working but not on chrome anymore, will tomorrow reinstall chrome.

reinstalled Chrome , and Pokal.dot, still the Chrome issue , this are the messages in the dev console : WebSocket connection to 'wss://tfchain.grid.tf/ws' failed: 
(anonymous) @ index.js:553
logger.js:81 2022-10-20 09:18:35          API-WS: disconnected from wss://tfchain.grid.tf/ws: 1006:: Abnormal Closure
b @ logger.js:81
error @ logger.js:162
value @ index.js:225

MacOS 12.6 Chrome is up to date
Version 106.0.5249.119 (Official Build) (arm64) , same issue on a Windows 11 Chrome and now on Firefox / Mac as well , I even changed DNS to 8.8.8.8 ( Google) , still not working

**Comment by coesensbert** [comment]
Don't forget to upgrade the terraform client also with:

`terraform init -upgrade`

**Comment by ramezsaeed** [comment]
please Re-open if this still happening.
