### ISSUE TITLE
How we implement a higher discount for dedicated nodes in mainnet?

### ISSUE THREAD

**Issue by weynandkuijpers** [threefoldtech/test_feedback#308]
H0w can we apply a higher discount?

- one percentage affect all dedicated nodes? 
- Per Farm?
- Per Server?

**Comment by AhmedHanafy725** [comment]
https://library.threefold.me/info/manual/#/manual__dashboard_portal_dedicated_nodes?id=billing-amp-pricing

**Comment by weynandkuijpers** [comment]
Okay - thank you.
