### ISSUE TITLE
Configuration Assistance,

### ISSUE THREAD

**Issue by Parkers145** [threefoldtech/test_feedback#310]
I am attempting to port the openwrt image to the grid.

This is the [image](https://firmware-selector.openwrt.org/?version=22.03.2&target=x86%2F64&id=generic)

I am familiar with the flist creation process and understand the basics of making a customized full vm image of ubuntu

There is another project that has enabled cloud-init for openwrt here with the [RC-Cloud](https://github.com/dtroyer/openwrt-packages) package. 

Where I require assistance is configuring rc.cloud to ensure proper deployment. 

Would you guys be Able to take a look at this one part of porting the image and see if there's a doable solution for testing? I can take it from there.

**Comment by ramezsaeed** [comment]
@delandtj 
can you please advice here..

**Comment by xmonader** [comment]
@sabrinasadik will assign this to you

**Comment by Parkers145** [comment]
Not around anymore, don't sweat it.
