### ISSUE TITLE
bad gateway config undetected on main net

### ISSUE THREAD

**Issue by Parkers145** [threefoldtech/test_feedback#316]
I was doing some maintenance tonight and restarted a node, on boot i noticed a public name space error leading me to find an error in its configuration. Should i have been notified this gateway config was down since the last update?

**Comment by ramezsaeed** [comment]
@sabrinasadik 
@PeterNashaat 
can u please have a look at this

**Comment by PeterNashaat** [comment]
@Parkers145  do you have a screenshot of the error message ?

**Comment by Parkers145** [comment]
This is the error it had and the actually issue was that the default
gateway address was wrong.

**Comment by Parkers145** [comment]
![1E33388F-323F-4150-B060-C555E6B05843](https://user-images.githubusercontent.com/44621168/200840478-780aa9e7-fb3d-4beb-9bd9-88d36a6f3c5a.jpeg)

**Comment by Parkers145** [comment]
![BBB7D92A-AD57-4270-A6FF-0D96EC28AA7D](https://user-images.githubusercontent.com/44621168/200840679-3a835dc4-6be0-47a9-bfac-a3c2df2bbde7.jpeg)

**Comment by mohamedamer453** [comment]
@Parkers145 can you please add node id

**Comment by Parkers145** [comment]
This was on 3049

**Comment by xmonader** [comment]
@PeterNashaat what is the status here?

**Comment by PeterNashaat** [comment]
- Issue fixed as there was an error in the pub ipv6 config.
