### ISSUE TITLE
Unable to reserve node 21 on mainnet

### ISSUE THREAD

**Issue by mohamedamer453** [threefoldtech/test_feedback#317]
### Description

While testing on mainnet i encountered an error with node 21 where i was not able to reserve it even though i got a message from the dashboard confirming my reservation, and almost 20 mins before this issue happened i already had this node reserved and had multiple deployments on it.

[Untitled_ Nov 7, 2022 3_30 PM.webm](https://user-images.githubusercontent.com/101194226/200325150-fc8b94d9-2380-45a9-9ba5-edd1298bc089.webm)

as seen in the video firstly i tried to reserve the node and it was successfully reserved according to the message from the dashboard but when i queried the node from gridproxy it had no rent contract and when i refreshed the dashboard the reservation was gone.

**Comment by mohamedamer453** [comment]
i tested the same scenario today on the same node and it worked, i reserved the node and after reservation i checked the proxy and it had the rent contract id.

![image](https://user-images.githubusercontent.com/101194226/200510552-e8582e95-8bb9-403b-a5f7-999319101946.png)

![image](https://user-images.githubusercontent.com/101194226/200510603-cfe5184a-965f-4146-8fc7-2132c42cae53.png)

and i also checked from graphql and the contract data was also available there.

![image](https://user-images.githubusercontent.com/101194226/200510851-c5c6ed31-17d5-4bf1-b1bd-66e6daa79b05.png)

however i'm still not sure what caused the issue with the reservation yesterday, i thought it might have been due to the high price of the node but immediately after it i reserved node 20 (has the exact same price `619.91`) for almost 2 hours before i ran out of tfts.
Also at the time that this issue happened i tried to reserve multiple other nodes and all of them were reserved successfully and rent contracts were created for each of them without any issues.

**Comment by DylanVerstraete** [comment]
I'm not sure how to debug this issue, maybe the dashboard was showing incorrect data? 

Please rent another node and I will check on chain to see if it works or not

**Comment by mohamedamer453** [comment]
I've rented the same node again on mainnet `node 21` and it's still rented and did not reset like it did last time, and i'm also able to get the rent info from the gridproxy.

![image](https://user-images.githubusercontent.com/101194226/203005984-152903eb-5662-4c3f-bc83-2fd5bfd67c64.png)

@DylanVerstraete the node is still rented if you want to check it from the chain.

**Comment by DylanVerstraete** [comment]
Looks good yes, can you deploy something on it? 

![image](https://user-images.githubusercontent.com/17138347/203006731-1c878a0e-1ffd-4aa9-a4c3-7f5abb2c50c6.png)

**Comment by mohamedamer453** [comment]
Successfully deployed a vm on it and it looks fine.

![image](https://user-images.githubusercontent.com/101194226/203008108-27e19839-3305-4ad4-a84c-a937ede9fe97.png)

**Comment by DylanVerstraete** [comment]
Great, can close this?

**Comment by mohamedamer453** [comment]
sure will close it since it was not reproducible
