### ISSUE TITLE
Main-net 20.04 image "apt upgrade -y" fails 

### ISSUE THREAD

**Issue by Parkers145** [threefoldtech/test_feedback#319]
![image](https://user-images.githubusercontent.com/44621168/200359827-9ed02bed-9b4b-42e3-9a1d-aa7a77059036.png)

was working on a deployment today that uses 20.04, when running apt upgrade -y this error occurred and the VM became unresponsive.

**Comment by Parkers145** [comment]
i deleted the VM and redeployed, the issue does reproduce 
![image](https://user-images.githubusercontent.com/44621168/200365307-a9e9db8e-13aa-4032-bb13-40b5eefef0a9.png)

i was able to not install this and continue with a fucntional VM but this is definitely something we want to have answers for ready.

**Comment by coesensbert** [comment]
Did you use this flist?

https://hub.grid.tf/tf-official-vms/ubuntu-20.04-lts.flist

**Comment by Parkers145** [comment]
It is happening it with the 20.04 and the 22.04 that are in the default drop down in the playground on testnet on nodes 219, 7, 2 and 124 I’m not actually sure where the links lead but it only happen on the first update if you tell it no

**Comment by xmonader** [comment]
closing in favor of https://github.com/threefoldtech/zos/issues/1821
