### ISSUE TITLE
 TC441 - Proof of utilisation 

### ISSUE THREAD

**Issue by dmitri-alleo** [threefoldtech/test_feedback#32]
The test case is not very clear on what's need to be done,

As explained in the documentation you should be running your own farm

Requirement:
https://app.testlodge.com/a/26076/projects/40893/requirements/38034#item_209172

**Comment by mohamedamer453** [comment]
TC441 was removed from the test suite as it was a documentation requirement and not a test case.

more info about this can be found here #81
