### ISSUE TITLE
testnet gateways seem to be malfuntiong?

### ISSUE THREAD

**Issue by Parkers145** [threefoldtech/test_feedback#321]
![image](https://user-images.githubusercontent.com/44621168/200712689-31237c27-ca3a-46f0-854c-ad308aea32e0.png)
i have been getting this error when deploying on multiple nodes to include, 2, 7, 124, but i think the issue is affecting all gateway workloads as ive been attempting troubleshoot funkwhale and peertube not deploying domains properly on testnet node 219.

**Comment by xmonader** [comment]
I believe the issue is coming from one of the nodes 2,7,124 that didn't reply in realtime during deployment
