### ISSUE TITLE
1000 VMs test cases

### ISSUE THREAD

**Issue by dmitri-alleo** [threefoldtech/test_feedback#33]
We should update the requirements and specifications of the test cases REQ125, REQ126, REQ127, REQ128,

As 1000 MVs cannot be provisioned to a single node due to IP limitations. 

We've had this previously on the Circles and the conclusion was that we should provision smaller number on VMs on multiple nodes and adjust the tickets accordingly

**Comment by despiegk** [comment]
why cant you, should not be public ip addr?
not we should do it, we need to know what happenes when we have so many
machines

**Comment by rkhamis** [comment]
@dmitri-alleo what's the state now?

**Comment by mohamedamer453** [comment]
Closing this issue since all the issues about the test cases related to 1000VMs (TC307 -> TC310) are being followed [here](https://github.com/threefoldtech/terraform-provider-grid/issues/212)
