### ISSUE TITLE
Failed to load 1 out of 2 Deployments, after my TFT got empty - refilling brought only one up.

### ISSUE THREAD

**Issue by fl0wm0ti0n** [threefoldtech/test_feedback#330]
Since yesterday I get the error "Failed to load 1 out of 2 Deployments" in the playground "https://play.dev.grid.tf/#/fullvm"
 
It seems it was caused due to an empty dev TFT pool in my account. After I refilled it some of my VMs got up and running but one is missing and i get this error.

grid: dev
VM name: dont remember
Node: 30 (or 31)
yggdrasil addres: 301:a9bd:9b77:ce71:5e7a:5024:80c:e542
flist: tf-official-vms/ubuntu-22.04
my twin id: 710

**Comment by despiegk** [comment]
devnet is very new right now, not sure we can trust it yet, its a very early build, 
best to test more on testnet right now

but thank you so much for reporting, we will check why this happened

**Comment by fl0wm0ti0n** [comment]
> devnet is very new right now, not sure we can trust it yet, its a very early build, best to test more on testnet right now
> 
> but thank you so much for reporting, we will check why this happened

i use dev cause its easy to get free tft to test, thats not possible in testnet (i think) is there a way?
