### ISSUE TITLE
devnet network issue

### ISSUE THREAD

**Issue by despiegk** [threefoldtech/test_feedback#331]
yesterday I deployed 3 VM's and after e.g. 30 min upto 60 min I lost all network access to it

machines where in ghent datacenter

I lost connection for yggdrasil as well as webgateway as wel ipv4 (which was only configured on one)

it might be issue with network in ghent or so but we need to know

I think having this monitoring will help we are talking about, lets make sure we measure networks and maybe also network traffic between machines

K.

**Comment by mohamedamer453** [comment]
can we get the contract id or the node id? otherwise it might be hard to debug.

**Comment by AhmedHanafy725** [comment]
checked the contracts and they went on the grace period, and the deployments got paused. can you please fund this account with some TFTs, and let's see if they will go back to being reachable?

**Comment by khaledyoussef24** [comment]
### verified on devnet

made a multiple deployment and multiple contracts and went to grace period
after funding the account all the deployment in the next cycle got back up and working

steps made:

1. go to weblets
2. deploy vm
3. transfer your wallet to make contracts go grace
4. fund the profile again
5. wait for an hour
6. make sure that deployments are back online again


![Screenshot from 2022-11-29 16-13-48](https://user-images.githubusercontent.com/110984055/204553603-a5ba9512-ca1d-4b66-838e-2d5968d7580a.png)

![Screenshot from 2022-11-29 16-15-36](https://user-images.githubusercontent.com/110984055/204553521-bef29729-668a-475f-a331-b25fcc45f1e9.png)
