### ISSUE TITLE
Being billed for contracts that I have canceled multiple days ago.

### ISSUE THREAD

**Issue by shng4you** [threefoldtech/test_feedback#333]
Since Monday I have been billed more than 20 TFT, but I should only have been billed about 7,5 TFT. I don't know for how long I am overpaying. I just noticed that my account balance is draining very fast. I've had many more deployments (and contracts) in the past. Normally when I deleted a deployment billing was stopped. I did not have to delete the contract seperately. This is not supposed to happen right? When I delete a deployment I would assume that it should also delete all corresponding contracts. There is no point in having contracts without deployments.
![image_1vjrm9b](https://user-images.githubusercontent.com/95933607/203973570-51585ba8-5c3c-4b39-841e-ff4c0ce6ad15.png)

**Comment by jakubprogramming** [comment]
![telegram-cloud-photo-size-4-5767069458874088550-y](https://user-images.githubusercontent.com/9266521/203987046-3d3070a7-59b8-4a80-bd32-6d84f8a06af6.jpg)

I realized that my account balance on Testnet was draining very fast, even though I only had a single very cheap VM deployment. As you can see in this screenshot there are zero active kubernetes deployments on my profile.

![telegram-cloud-photo-size-4-5767069458874088551-y](https://user-images.githubusercontent.com/9266521/203987101-2e0d9826-ab23-4289-9fcd-df2d65100058.jpg)

Then under contracts I could see that even though I had zero kubernetes deployments, there were two active contracts still existing.

This is not supposed to happen right? When I delete a deployment I would assume that it should also delete all corresponding contracts. There is no point in having contracts without deployments.

**Comment by DylanVerstraete** [comment]
@jakubprogramming Hi, can you provide me your twin ID and network please?

**Comment by jakubprogramming** [comment]
Yes of course

twin ID: 488 
Nework: testnet

**Comment by DylanVerstraete** [comment]
There is still a deployment which is active:

```
      {
        "resourcesUsed": {
          "cru": "1",
          "hru": "0",
          "mru": "536870912",
          "sru": "16630415360"
        },
        "numberOfPublicIPs": 0,
        "contractID": "13537"
      }
```

**Comment by jakubprogramming** [comment]
Yes I know. That is not the problem. I have explained the problem above. The exisiting deployment is fine.

**Comment by xmonader** [comment]
@DylanVerstraete do we know what's happening? is it possibly related to discounts on the TFT balance?

**Comment by DylanVerstraete** [comment]
@jakubprogramming is this resolved now?

**Comment by jakubprogramming** [comment]
For me personally it was resolved as soon as I deleted the active contracts. 
I don't know if it could potentially still happen to others. IMO every time an active deployment is deleted its corresponding contract should as well. Thats what usually happens too. In my case it did not and the contract had to be deleted manually.

**Comment by xmonader** [comment]
Will close, please reopen if it happens again
