### ISSUE TITLE
Some questions around microVM and community-created-containers

### ISSUE THREAD

**Issue by fl0wm0ti0n** [threefoldtech/test_feedback#334]
how do i know if my own flist-container is running? i made a postgres and a dgadmin container from up and running docker containers. env vars already set up. uploaded to flist hub. https://hub.grid.tf/flowmotion.3bot

now i made 2 deployments but i cant connect at all... i can just ping them in ygg and with public ipv4... but ping says nothing... 

Do my questions:
can i check if it is running well without connecting over the docker given ports? (ssh doesnt exists in this docker containers)
how is this microvm concept built in case of starting a container and set up the right env-vars?
i preconfigured my images with env vars and ports so is this enough? is the threefold engine booting it up well?
what is this ""entrypoint": "/sbin/zinit init""
some steps whats necessary to boot a container on the grid would be nice.

feedback: a status of containers and vms would be nice, just a , "running", "booting", "error"

so you can chack maybe this are my deployments:
1 | testpostgres | 162.205.240.240 | 2600:1700:c1e0:1150:3013:76ff:fe76:c858 | 300:e130:e232:e78c:85ba:9a48:c106:bf83 | flowmotion.3bot/pgadmin_image_20221125
 | 2 | testpostgres1 | 162.205.240.241 | 2600:1700:c1e0:1150:cc78:9ff:fe61:ecfb | 300:9bd8:6f95:d606:ace5:7898:c019:7fdd | flowmotion.3bot/postgres_image_20221125
 
 Thaanks alot

**Comment by 0oM4R** [comment]
Hello,
For the first question, To check if the machine is running.
I tried to ping the provided IPs and it works fine 
**testpostgres**
![image](https://user-images.githubusercontent.com/62248851/204134442-68d77fb5-c11c-43d9-98a9-bb34f88c21a2.png)
**testpostgres1**
![image](https://user-images.githubusercontent.com/62248851/204134425-d3e404db-d10a-4840-a6a3-73180397ecd5.png)

some other ways to check :
1. **Ssh** over it 
to enable ssh, you can add this [script](https://github.com/0oM4R/kassem_telebot/blob/main/start.sh) to your docker file
> Note: the last two lines in the script is to run the application 

2. Apply one of your application scenarios
for example, if we have a web app that runs over port 8080 
so try to type in the browser `162.205.240.240:8080` this is the simplest scenario

> Note: there's no way to guarantee that the machine is behaving the way it should be and that the containers inside it running as they should without ssh to the machine

### About env
The env that is configured in the docker file is not accessible after building the image, so if you need to add env to the machine in deploying phase, you can do it with 
1. Add button in weblet, please check the environment variable section in [manual](https://library.threefold.me/info/manual/#/manual__weblets_vm) 
2. create a script to inject those variables before the start of the program check this [example](https://github.com/0oM4R/kassem-ToDo/blob/ubuntu/frontend/build-env.sh)

### About the entry point 
It is the starting command for the application, it needs to be the same as the CMD or ENTRYPOINT that is defined in the docker file.

finally, the manual gives you the steps to deploy the machine but if you mean boot a container inside the machine you have to ssh into the and use docker commands inside the machine or write a script to do so 

### Deployment status 
After the deployment process is completed, the dialogue displays deployment details. navigate to json tab then you can find the field `status` which can have three values, 
![image](https://user-images.githubusercontent.com/62248851/204141111-e64013bf-c474-4695-a0e1-227ff5caf782.png)

> Note: in the bottom of the page you can see a list of all of the virtual machines you deployed. you can click on `Show details `for more details
- `init` -> the machine is starting
- `error` -> if the machine has an issue 
- `ok` -> the machine is running well
in case of an error, the `message` field will have what is the error in the machine

**Comment by fl0wm0ti0n** [comment]
> 
Hello , thanks alot for your infos!

**Comment by fl0wm0ti0n** [comment]
hello, thanks for your detailed infos!!

About reaching my containers, i know i can ping thema but i don't know if this means something. for example if i ping a vm it doesn't mean the app on the vm is runnung. The same can be for my container. i don't know how the layers on zos are built up, so who is answering on the ping? zos on the node or the container.

I preconfigured these containers with following ports 82:80 and 5432:5432 but i cant reach them with this ports
the webinterface for example should reachable via https://162.205.240.240:82/ but isnt. So i think the container got not well deployed or got not startet with the correct configs.

>_to enable ssh, you can add this [script](https://github.com/0oM4R/kassem_telebot/blob/main/start.sh) to your docker file_

i can activate ssh on a dockerimage like postgres? i thought containers are minimal with just the important stuff so the app can run. I hope I can change a dockerfile of an image :D I just developed my own container apps in the past there i had to create my own dockerfile, but postgres is not developed from me.


>_"Note: the last two lines in the script is to run the application"_ 

you mean the ssh application? or the postgres? how should i start the application? isn't the container the thing i have to start? like in docker with "`docker run <name> -p 82:80 -e ENV_PASSW=password <image>`"

>_"The env that is configured in the docker file is not accessible after building the image, so if you need to add ENV to the machine in deploying phase, you can do it with"_

you mean as i made an image out of the container the configured ENVs got deleted again?

>_"create a script to inject those variables before the start of the program check this"_

where to i create this script? in the container before i create an image? where to i paste this script?


>It is the starting command for the application, it needs to be the same as the CMD or ENTRYPOINT that is defined in the docker file.
>finally, the manual gives you the steps to deploy the machine but if you mean boot a container inside the machine you have to ssh into the and use docker commands inside the machine or write a script to do so

as I use an already done image from docker registry  i don't have a dockerfile where i configured something. I just use "`docker run <name> -p 82:80 -e ENV_PASSW=password <image>`" and "`docker start <containername>`".
so in case of postgres [this is the dockerfile](https://github.com/docker-library/postgres/blob/75d0c1135e1cfd183bf7ee0970b7031986b0710d/15/bullseye/Dockerfile) so that does mean this `ENTRYPOINT ["docker-entrypoint.sh"]` would be the entry point?


about the status. does "ok" mean the container is running or the it is just deployed without an error?

thanks alot

**Comment by fl0wm0ti0n** [comment]
for example https://hub.docker.com/layers/library/postgres/latest/images/sha256-7d17c721d2641793afd73d95400010604fddf61f0d1b462dcc95ebad1e7b6205?context=explore

does the zos containerization execute all this steps? again? i thought no because the image is already created. so i dont think configuring the dockerfile would help?? or did i missunderstood something?

**Comment by 0oM4R** [comment]
> I preconfigured these containers with following ports 82:80 and 5432:5432 but i cant reach them with this ports
the webinterface for example should reachable via https://162.205.240.240:82/ but isnt. So i think the container got not well deployed or got not startet with the correct configs.

I can't help that much with this point, but if you ping the VM so the VM is answering not any of the containers, so I suggest ssh to the machine to verify that the containers are running well.

> i can activate ssh on a dockerimage like postgres? i thought containers are minimal with just the important stuff so the app can run. I hope I can change a dockerfile of an image :D I just developed my own container apps in the past there i had to create my own dockerfile, but postgres is not developed from me.

yes It's better to have a minimal image but for debugging purposes you can add ssh to the image and  after verifying all is good so you can remove the ssh
#### To add ssh to a Postgres image or any image you can check this [repo](https://github.com/0oM4R/postgres_ssh) that will make that clear to you.

> you mean the ssh application? or the postgres? how should i start the application? isn't the container the thing i have to start? like in docker with "docker run <name> -p 82:80 -e ENV_PASSW=password <image>"

To start Postgres  in postgres you have a command, incase of using postgres image `/usr/local/bin/docker-entrypoint.sh postgres`,  but docker needs more than that. In general, I recommend checking this repo  [zinit](https://github.com/threefoldtech/zinit)

> you mean as i made an image out of the container the configured ENVs got deleted again?

I'm not sure what you mean but the ENVs that have been used in the build image aren't accessible after booting the VM, so you need to add the ENVs that you need to use during the running of the VM as I mentioned.

> where to i create this script? in the container before i create an image? where to i paste this script?


This script can be used after building the image, booting the VM, and before running the app whatever it is 
So the sequence will be 
1. Build the image 
2. Deploy VM 
3. Run injection script 
4. Run the app
Where to put this script doesn’t matter that much but you of course have to `COPY script.sh / ` in Dockerfile


If you build your own image, you need to make sure that you type the entrypoint in the absolute path, in the case of docker as I mentioned I recommend to use zinit
If you are using an image from the docker hub so exactly you need to type the entry point that is mentioned in the image in the absolute path, 
In the case of Postgres, they are using CMD Postgres after the entry point so the following is what is the final entrypoint an absolute path.
‘/usr/local/bin/docker-entrypint.sh postgres’


“Ok” means that the VM deployed without error

**Comment by mohamedamer453** [comment]
Closing this issue since all of the questions were answered. @fl0wm0ti0n Please feel free to reopen this issue if you need more clarification or have more questions about this issue.

**Comment by fl0wm0ti0n** [comment]
Thanks a lot @0oM4R that are many helpful information's i will try it out with your hints!

**Comment by fl0wm0ti0n** [comment]
@0oM4R I made some tests with your hints and made some changes so it works all well on local docker
in my tests I reach postgres, pgadmin and ssh very well over local network with all ports.

But if I deploy the same on the grid it doesn't work no ssh, neither of the needed ports. only pinging works.

Im happy and thankful if you can look into my [repo](https://github.com/fl0wm0ti0n/tf_custom_containers) where I uploaded the dockerimage and the scrips. in my opinion it should work.. so maybe on zos something is working wrong? it seems the script doesn't get executed

Edit: the commands how I created the tars:
  docker image build -t custom_postgres_ssh .
  docker save custom_postgres_ssh | gzip > custom_postgres_ssh.tar.gz

That's how I deployed them on the grid:
            
```
              {
    "version": 0,
    "contractId": 15530,
    "nodeId": 49,
    "name": "PostgresTest1",
    "created": 1670712377,
    "status": "ok",
    "message": "",
    "flist": "https://hub.grid.tf/flowmotion.3bot/postgres_ssh_20221210.flist",
    "publicIP": {
        "ip": "162.205.240.240/25",
        "ip6": "2600:1700:c1e0:1150:7cfc:f9ff:fe00:49df/64",
        "gateway": "162.205.240.254"
    },
    "planetary": "300:e130:e232:e78c:5a22:e136:fecf:a4e9",
    "interfaces": [
        {
            "network": "NW4399afbc",
            "ip": "10.20.2.2"
        }
    ],
    "capacity": {
        "cpu": 8,
        "memory": 8192
    },
    "mounts": [
        {
            "name": "DB100",
            "mountPoint": "/mnt/db100",
            "size": 107374182400,
            "state": "ok",
            "message": ""
        }
    ],
    "env": {
        "SSH_KEY": "removed for github issue"
    },
    "entrypoint": "/start.sh",
    "metadata": "{\"type\":\"vm\",\"name\":\"PostgresTest1\",\"projectName\":\"\"}",
    "description": "",
    "corex": false
}
```
 
```
              {
    "version": 0,
    "contractId": 15532,
    "nodeId": 49,
    "name": "PgAdminTest1",
    "created": 1670712676,
    "status": "ok",
    "message": "",
    "flist": "https://hub.grid.tf/flowmotion.3bot/pgadmin_ssh_20221210.flist",
    "publicIP": {
        "ip": "162.205.240.241/25",
        "ip6": "2600:1700:c1e0:1150:c491:bdff:fe7f:31e0/64",
        "gateway": "162.205.240.254"
    },
    "planetary": "300:e130:e232:e78c:2ab:c744:70e1:e03a",
    "interfaces": [
        {
            "network": "NW1cb128c4",
            "ip": "10.20.2.2"
        }
    ],
    "capacity": {
        "cpu": 8,
        "memory": 8192
    },
    "mounts": [
        {
            "name": "DB50",
            "mountPoint": "/mnt/db50",
            "size": 53687091200,
            "state": "ok",
            "message": ""
        }
    ],
    "env": {
        "SSH_KEY": "removed for github issue"
    },
    "entrypoint": "/start.sh",
    "metadata": "{\"type\":\"vm\",\"name\":\"PgAdminTest1\",\"projectName\":\"\"}",
    "description": "",
    "corex": false
}
```
 
 thanks alot

**Comment by fl0wm0ti0n** [comment]
but this case here is the important issue :D im stuck here :(

**Comment by 0oM4R** [comment]
I'm working on it, but for the current time, I recommend you use [a Docker image converter](https://hub.grid.tf/docker-convert).
I will follow up with you as soon as I figure out what the error is.
Sorry for being late.

**Comment by fl0wm0ti0n** [comment]
No hurry!! Im just happy if someone can say if it is a threefold issue, a container issue or a Layer 8 issue. 
I have time its just testing right now ;) for me and for us ;)

The docker converter I tried and I got no connection, but thanks for remebering me! It was not an error of the container, it was an error of the node of the farm. So yes I can test it again :D

**Comment by 0oM4R** [comment]
I'm happy to say that is not an issue :D
if you are using tar.gz so you have to include all env in the start script, as you use an official image and it has many envs that are not accessible on booting, docker converter handles it, but if you want to use tar you have to use docker inspect to get all the env on the image, then add it to start.sh or add it to env in weblete. 
to cut off your time there are the needed env for postgres image :
````
 PATH="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/lib/postgresql/15/bin"
 LANG="en_US.utf8"
 PGDATA="/var/lib/postgresql/data",
 POSTGRES_PASSWORD=postgres
````
And there are the instance logs : 
![image](https://user-images.githubusercontent.com/62248851/208432923-485582b3-6fe2-4055-990b-cde9fd669f09.png)

**Comment by fl0wm0ti0n** [comment]
> 
Thanks alot!
Im sorry there are some questions open :)
As I have the envs in my dockerfile they are already set up. I have tested it if I run my dockerfile with the envs, they are then in the image and I don't have to run, for example, "POSTGRES_PASSWORD=postgres" anymore.

But lets say on threefold its necessary to put them into the start script.. That doesn't explain why my SSH does not working :(
the SSH-Stuff its all in the script. You know my [repo](https://github.com/fl0wm0ti0n/tf_custom_containers) 
if I test it with docker ssh is running well.

greets flow

**Comment by 0oM4R** [comment]
I see that `start.sh` need to be modified.
as you are using alpine so the ssh config script should be : 
````
#!/bin/sh
mkdir -p /root/.ssh
chmod 0700 /root/.ssh 
passwd -u root 
echo "$SSH_KEY" > /root/.ssh/authorized_keys 
apk add openrc openssh 
ssh-keygen -A 
echo -e "PasswordAuthentication no" >> /etc/ssh/sshd_config 
mkdir -p /run/openrc 
touch /run/openrc/softlevel
rc-status;
rc-service sshd start
````
then you need to get the right env using image inspect as we discussed, 
````
export PATH="$PATH:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
export PYTHONPATH="/pgadmin4"
export PGADMIN_DEFAULT_EMAIL="initial@postgres.com"
export PGADMIN_DEFAULT_PASSWORD="postgres"
````
finally, this image uses `/pgadmin4` as `workdir`
![image](https://user-images.githubusercontent.com/62248851/209541801-254d8e17-6d3a-445e-9ec2-3bafacf2dd5a.png)

we need to cd to this dir before running `entrypoint.sh` which is located in /
![image](https://user-images.githubusercontent.com/62248851/209541943-44fdf882-c7e6-4a55-83fb-aa4c492aee41.png)
````
cd pgadmin4/
/entrypoint.sh
````

**Comment by xmonader** [comment]
I've to close this thread, it's a never ending discussion. Please if you have other questions open them separately
