### ISSUE TITLE
more details for Terraform resources

### ISSUE THREAD

**Issue by fl0wm0ti0n** [threefoldtech/test_feedback#335]
The most terraform resources are clear so you don't need to know much to get the reason for it for example disks, vm-hartware etc.

But there are some "resources" and "data sources" which are not clear how they work or how they work together. By some you can recognize for what they are planned to be, but don't know how.

So my feedback and wish is, to have more details and examples for resources which are more complex.
Where? Here: [terraform-registry]( https://registry.terraform.io/providers/threefoldtech/grid/latest/docs)

Some examples, but there is more:

**Domain&Gateway:**
grid_fqdn_proxy (Resource)
Description: Resource for deploying gateway domains.
-> feedback: has same desc. as the resource after, realworld example needed

grid_name_proxy (Resource)
Description: Resource for deploying gateway domains.
-> feedback: has same desc. as the resource before, realworld example needed

grid_gateway_domain (Data Source)
Description: Data source for computing gateway name proxy fqdn.
-> feedback: realworld example needed

**Networking:**
ip_range (String) 
Description: Network ip range
-> feedback: i cant enter here what i want i realized... so why isn't it then read only?

add_wg_access (Boolean) 
Description: Whether to add a public node to network and use it to generate a wg config
-> feedback: description doesn't really say something.

nodes_ip_range (Map of String)
Description: Computed values of nodes' ip ranges after deployment
-> feedback: i cant enter here what i want i realized... so why isn't it then read only?

**Deployment/vm/k8s:**
ip_range (String)
Description: IP range of the node (e.g. 10.1.2.0/24)
-> feedback: it  seems useless cause it seems defined from network? 

ip (String)
Description: The private wg IP of the Zmachine
-> feedback: i cant enter here what i want i realized... it generates its own IP... so why isn't it then read only?

entrypoint (String)
Description: command to execute as the Zmachine init
-> feedback: i really don't know what to write here... what i can do here.. some examples would be nice

token (String)
Description: The cluster secret token
-> feedback: for what used? manually generated? or given from elsewhere?

**QSFS:**
-> feedback: nearly all parameters needs more details :) how they work together. shards, groups etc?

Some extra thoughts to k8s resource:

The resource for kubernetes has less parameters and options than for deployments/VM for example, does that mean i cant use a qsfs or zdb with kubernetes? so also here some infos please :).

**Comment by xmonader** [comment]
closing in favor of https://github.com/threefoldtech/terraform-provider-grid/issues/375
