### ISSUE TITLE
Help with writing a post about how to move an existing Mastodon server to the grid

### ISSUE THREAD

**Issue by samtaggart** [threefoldtech/test_feedback#336]
Would like to publish something on our blog or forum about how to move an existing Mastodon server to ThreeFold. Will be targeting admins of notable servers with this, so please note we have to consider the possibility of what an admin of a 50k-100k community would need to know, as well as anybody managing a smaller server. Topics would need to include:

- How to move your Mastodon server to ThreeFold
- What it will cost ...
- How to monetize your server
- How to scale your server
- ... (what else?)

**Comment by samtaggart** [comment]
Hi @ramezsaeed any estimated time you'll have this ready?

**Comment by xmonader** [comment]
@Mahmoud-Emad @hossnys please work together on providing the data for this

**Comment by xmonader** [comment]
https://github.com/threefoldfoundation/info_manual3/pull/142/files
