### ISSUE TITLE
Devnet & Qanet nodes are appearing as down

### ISSUE THREAD

**Issue by mohamedamer453** [threefoldtech/test_feedback#343]
### Description 

Devnet & Qanet nodes are appearing as down, however i can still access my previous deployments on both networks.

### Devnet

![image](https://user-images.githubusercontent.com/101194226/205883869-3256fb84-8fbd-45c3-8325-aefc6d78008d.png)

![image](https://user-images.githubusercontent.com/101194226/205873873-3138ace1-b585-4d00-bc88-22f232406961.png)

### Qanet

![image](https://user-images.githubusercontent.com/101194226/205883940-34be1a45-e737-4068-a252-c123a5a4f29c.png)

![image](https://user-images.githubusercontent.com/101194226/205873789-3e6b7ed6-7565-411a-bb4c-082ecbfd70ea.png)

**Comment by coesensbert** [comment]
Devnet: https://github.com/threefoldtech/tf_operations/issues/1300

QAnet: https://github.com/threefoldtech/tf_operations/issues/1298

**Comment by coesensbert** [comment]
devnet resolved

**Comment by mohamedamer453** [comment]
devnet nodes are back and it's working again. but qanet nodes are still down.

![image](https://user-images.githubusercontent.com/101194226/206454982-729dccfc-f782-4205-8402-9bab02cef7cf.png)

**Comment by ramezsaeed** [comment]
QA net fixed too
