### ISSUE TITLE
TC440:  ipfs server can run over planetary network

### ISSUE THREAD

**Issue by georgeconstantinou** [threefoldtech/test_feedback#36]
Planetary=true, 
Able to ssh into the node via ygg address, 
able to wget and start ipfs, 
able to remap the ports,

but not able to get any data from the host via the ygg IP address

**Comment by mohamedamer453** [comment]
I followed the steps mentioned in [TC440](https://app.testlodge.com/a/26076/projects/40893/suites/195345?expand_section=309756#case_3429055) and i didn't face any problems with it.

Firstly i deployed a VM with planetary network enabled and ssh'd to the VM using yigg IP and then i followed the steps mentioned in the [documentation](https://docs.ipfs.io/install/command-line/#official-distributions) to install IPFS , and it was installed successfully.

![image](https://user-images.githubusercontent.com/101194226/168986824-de5c535d-cde0-48ca-af8f-d1a0fbf15b75.png)

and then from the [quick start guide](https://docs.ipfs.io/how-to/command-line-quick-start/#initialize-the-repository) i followed these steps to initialize and start IPFS.

i executed `ipfs init`

![image](https://user-images.githubusercontent.com/101194226/168987265-6ed219a4-9c04-48c2-a380-890b822c92d9.png)

then i executed the provided command for readme file.

![image](https://user-images.githubusercontent.com/101194226/168987570-11555fba-6ffd-4bc6-a5b7-9719b780554d.png)

and finally `ipfs daemon` to start IPFS 

![image](https://user-images.githubusercontent.com/101194226/168987804-ea6e82d8-a38a-484f-9568-4356d4d2de4d.png)

I also updated the test steps with the installation steps mentioned in the docs and added the commands i used from the quick start guide.

I'm closing this issue for now as i didn't find any issues with the test case description/steps. Please reopen this issue if it didn't solve your problem and if what i mentioned is not related to your issues please provide more info/logs and steps on how to reproduce this issue.
