### ISSUE TITLE
after deleting cookies ProfileManager doesnt work anymore 

### ISSUE THREAD

**Issue by fl0wm0ti0n** [threefoldtech/test_feedback#361]
i deleted all cookies from https://play.dev.grid.tf/ now the profilemanager is destroyed... i can add endless profiles. they dont get saved

browser: chrome

**Comment by fl0wm0ti0n** [comment]
after 1 hour or so it worked...  performance issue maybe?

**Comment by ramezsaeed** [comment]
a lot of changes are going on in profile manager and this issue will net be valid anymore.

https://github.com/threefoldtech/grid_weblets/issues/1119
