### ISSUE TITLE
issue in deploying many test workloads on pub nodes

### ISSUE THREAD

**Issue by Parkers145** [threefoldtech/test_feedback#364]
I have been attempting to setup workloads around the world and Im running into significant issues with public configs that are not functioning. I am consistently finding situations where only some nodes in a farm are able to successfully deploy  a public ip. As a general inventory i attempted to deploy a workload with 4gb of ram 4 cores 15gb ssd, ipv6 and ipv4 without planetary.  I attempted this on 26 different nodes showing resources available to support the workload. of those 26 nodes I was able to successfully deploy on 6 of them, of that 6 only 4 were successful on the first attempt. here is a inventory of the results. nodes that worked are highlighted. 

Better results next post

interestingly, one of these nodes that doesnt work is mine, and it shares a connection, switch and farm with a working node and it has this public config error, like most of these nodes, 

![image](https://user-images.githubusercontent.com/44621168/208341868-bf292efe-0d6e-43ee-954a-fb7a16342a91.png)

this is being caused by the persistent storage of the public config on the disk as this node was using an integrated nic, but i later installed a new SFP+ nic, NIC 2 is still using the rj45 port with no cable in it. this means any node with a public config that ever has its nic 2 lan cable moved to a new port will cease to function until 1.) the drives are wiped or 2.) the public config file is removed. 

1.) I need to know what file i need to remove to get 3049 to stop using an offline nic 
2.) is there a way to make a node check that nic persisted into the file is actually up?

**Comment by Parkers145** [comment]
![image](https://user-images.githubusercontent.com/44621168/208354467-a01ef3d1-64fb-4349-abda-a072d0a52bf0.png)

after filtering out certified farms i have tested 2 nodes on all farms with available public ips, these are the results

the ip addresses associated with farms 13,14,33,45,84,90,138,209,274,276,297,301,360,405,546,1114,230,2148,2326,2421,2422,2446,2460,2622, and 2659 

are non  functional or i could not find a functional node, farms 305 and 1956 are partially functional

**Comment by Parkers145** [comment]
[IP Function Testing.xlsx](https://github.com/threefoldtech/test_feedback/files/10256229/IP.Function.Testing.xlsx)

here is the spreadsheet that i used to determine what nodes to test, i tested the lowest and highest node id in all farms with public ips, not including foundation and greenedge.

**Comment by despiegk** [comment]
amazing work, we will fix the issues you find in our next release 3.9
we are finishing the 3.8 right now

**Comment by DylanVerstraete** [comment]
A fix is already incorperated in 3.8, I will cross check with your data and reply with my findings.

**Comment by DylanVerstraete** [comment]
Farms we found with invalid public ips: 

`13,   33,   45,  138,  175, 209,  301,  311,  363,  367, 405, 1114, 1459, 1790, 2148, 2326, 2331, 2849, 2853`

Some farms that you found do not show up at our side.

Farm 14: no public ips
Farm 84 (Teis): Looks correct, not sure why you say it's now working?
Farm 90: Looks correct as well
Farm 274: no public ips
Farm 276: no public ips
Farm 297: no public ips
Farm 360: no public ips
Farm 546: no public ips
Farm 230: no public ips
Farm 2421: Looks correct
Farm 2422: Looks correct
Farm 2446: no public ips
Farm 2460: no public ips
Farm 2466: Looks correct
Farm 2659: no public ips

**Comment by Parkers145** [comment]
I only tested farm 84, node 941 and and 4164 for ability to deploy a public ip workload, I actually believe there are other nodes in 84 that are working, I’ll put it on my list with 305 for a top to bottom.

**Comment by despiegk** [comment]
we need feedback

**Comment by DylanVerstraete** [comment]
As said above, this will be fixed with the 3.8 release.

**Comment by A-Harby** [comment]
Checked few farms and found some farm doesn't have any more invalid public IPs. 
Like. Farm 13
![image](https://user-images.githubusercontent.com/109473873/214617748-2db1d28c-210a-4ec8-98b1-8d93e252e1bc.png)

And found some other that have available public IPs.
Like.
Farm 33.
![image](https://user-images.githubusercontent.com/109473873/214618700-9125ad3b-690f-4ed3-a598-22ae5cd8f144.png)
Which I was able to deploy VM with IPV4 and IPV6 successfully.
![image](https://user-images.githubusercontent.com/109473873/214618898-447951fc-059e-4b23-857f-b58da75454fd.png)
And Farm 84 (Node 4164 and 1654), 
![image](https://user-images.githubusercontent.com/109473873/214624380-49fd7e5e-bc7c-4dff-a13e-02bb93538989.png)
![image](https://user-images.githubusercontent.com/109473873/214624425-be19274d-45f0-48bb-8b4c-1bcc7636651e.png)

But there is still farms that face the same issue
Like Farm 14
![image](https://user-images.githubusercontent.com/109473873/214620747-04807dfa-7d93-4300-b4ee-8b2a280731b9.png)
![image](https://user-images.githubusercontent.com/109473873/214621097-d0d25c7d-ffdf-4bda-aa81-7c2e2dd5986b.png)

**Comment by AhmedHanafy725** [comment]
for farm 14, there is no public ips on the chain 
![image](https://user-images.githubusercontent.com/41957921/215748702-19d1c748-aac2-442f-ab38-225f285afdae.png)

but on graphql there is one public ip, I think this ip was deleted
![image](https://user-images.githubusercontent.com/41957921/215748644-64ae0e5d-f33c-42cc-8baf-5bae889af9b6.png)

@DylanVerstraete I think this issue was solved before on devnet, maybe the fix is not deployed on mainnet yet, no?

**Comment by DylanVerstraete** [comment]
Yes, it will be fixed in 3.8

**Comment by DylanVerstraete** [comment]
3.8 was deployed last week, closing
