### ISSUE TITLE
Failed to Deploy on node .... due to Type Error: Cannot read properties of undefined (reading 'data')"

### ISSUE THREAD

**Issue by weynandkuijpers** [threefoldtech/test_feedback#369]
Deploying a flist results in ```Failed to Deploy on node .... due to Type Error: Cannot read properties of undefined (reading 'data')"```

**Comment by xmonader** [comment]
please state which environment you're testing against

**Comment by coesensbert** [comment]
and node id + play/terraform?

**Comment by sameh-farouk** [comment]
devnet

playground and ts_client have the same issue

all nodes seem to have this issue except 33 and 34 work fine

nodes tested and failed 13, 17, 29, 30, 31, 32
note: 33, and 34 are the most recently reasserted nodes based on uptime

**Comment by coesensbert** [comment]
Could this be related to the GLIBC issues since ZOS upgrade? These are devnet node 17 logs

https://mon.grid.tf/explore?orgId=1&left=%5B%22now-3h%22,%22now%22,%22Loki%22,%7B%22refId%22:%22A%22,%22expr%22:%22%7Bnetwork%3D%5C%22development%5C%22,node%3D%5C%225H2rCQmzeBG2Bdd1U9HAqeE8yeAmEiHSsnUVhDdUbrqV5NHZ%5C%22%7D%22%7D%5D

**Comment by xmonader** [comment]
@muhamadazmy any ideas?

**Comment by weynandkuijpers** [comment]
> please state which environment you're testing against

Apologies, I did not think about mentioning this.  It was something that was reported in a telegram group, and I took it forward to report as an issue. Next time I'll ask for this. Pretty sure this was mainnet.

**Comment by weynandkuijpers** [comment]
Is this one done, can we close it or does it need more investigation?

**Comment by coesensbert** [comment]
I did not encounter it anymore recently

**Comment by despiegk** [comment]
close or not?

**Comment by coesensbert** [comment]
Think we can close yes, no GLIBC error's anymore on any net
