### ISSUE TITLE
Very slow download speed on the testnet nodes

### ISSUE THREAD

**Issue by georgeconstantinou** [threefoldtech/test_feedback#37]
When a single node is provisioned to the testnet, trying to download a 26 MB file

```plaintext
wget https://dist.ipfs.io/go-ipfs/v0.11.0/go-ipfs_v0.11.0_linux-amd64.tar.gz
```

it often times out for 30 - 60 seconds and then resumes the download with the speed of 75 - 150 kb/s.

For the 26 MB file took around 20 minutes with wget

**Comment by rkhamis** [comment]
@coesensbert ideas?

**Comment by delandtj** [comment]
errr... is this still relevant ? On what node?

**Comment by coesensbert** [comment]
Not immediately, also have workloads on testnet grid but no issues with bw. Could also not reproduce

```
coesensb@lbtestcluster03:~$ wget https://dist.ipfs.io/go-ipfs/v0.11.0/go-ipfs_v0.11.0_linux-amd64.tar.gz
--2022-04-21 10:02:13--  https://dist.ipfs.io/go-ipfs/v0.11.0/go-ipfs_v0.11.0_linux-amd64.tar.gz
Resolving dist.ipfs.io (dist.ipfs.io)... 2602:fea2:3::1, 209.94.78.1
Connecting to dist.ipfs.io (dist.ipfs.io)|2602:fea2:3::1|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 27860624 (27M) [application/gzip]
Saving to: ‘go-ipfs_v0.11.0_linux-amd64.tar.gz’

go-ipfs_v0.11.0_linux-amd64.tar.gz         100%[======================================================================================>]  26.57M  61.8MB/s    in 0.4s    

2022-04-21 10:02:14 (61.8 MB/s) - ‘go-ipfs_v0.11.0_linux-amd64.tar.gz’ saved [27860624/27860624]
```

**Comment by dmitri-alleo** [comment]
I believe the Grid's performance has improved greatly since the moment this was reported, We've reported similar issues back then, 

Re-runing the same `wget` test now takes just a few seconds to download the go-ipfs, and the speed goes up to 10 MB/s

The test was performed on the Testnet, 
the Mainnet should be faster than the Testnet

**Comment by ramezsaeed** [comment]
@delandtj please check
