### ISSUE TITLE
VM is deleted after the qa upgrade

### ISSUE THREAD

**Issue by Omarabdul3ziz** [threefoldtech/test_feedback#371]
I had a VM on QA three days ago and couldn't reach it anymore
it has the public IP:  185.69.167.86 and it is not pingable now

and checking graphql I found my twin has no contracts 
![image](https://user-images.githubusercontent.com/32527347/211264047-ba982f72-9340-4b9c-8cfa-29f154f4443f.png)

**Comment by khaledyoussef24** [comment]
I faced the same problem I had a vm and k8s i was using in testing 3 days ago i couldn't shh on them

**Comment by DylanVerstraete** [comment]
@Omarabdul3ziz I see that you are trying to look up a twin with ID 220, that does not exist on Qanet. The highest created twin ID is 144. Are you sure you are referring to the correct network?

**Comment by DylanVerstraete** [comment]
@khaledyoussef24 Can you give me some details about your twin?

**Comment by DylanVerstraete** [comment]
@Omarabdul3ziz It looks like your contract is in grace period:

```
{
  version: 4
  state: {
    GracePeriod: 3,060,402
  }
  contractId: 4,716
  twinId: 17
  contractType: {
    NodeContract: {
      nodeId: 3
      deploymentHash: da514dd484cce2651efda0a5606a031d
      deploymentData: {type:vm,name:qaenv2,projectName:Fullvm}
      publicIps: 1
      publicIpsList: [
        {
          ip: 185.69.167.86/24
          gateway: 185.69.167.1
          contractId: 4,716
        }
      ]
    }
  }
  solutionProviderId: null
}
```

Also note the twin ID is different from what you are trying to query

**Comment by Omarabdul3ziz** [comment]
@DylanVerstraete yes due to an issue in the QA playground it shows my test net twin. just checked the dashboard and my twin id is 17
but it has about 85 TFT is that not enough for the contract resources?

**Comment by DylanVerstraete** [comment]
It's in grace state for a while now, I don't know exactly how much this deployment costs but If I were you I would top up my balance to get it back to created state :)

**Comment by Omarabdul3ziz** [comment]
okay thanks
