### ISSUE TITLE
(Mainnet verification) [Bug 🐞]: Contracts continue billing in grace period

### ISSUE THREAD

**Issue by Parkers145** [threefoldtech/test_feedback#379]
### What happened?

some of my test deployments were left up unintentionally, i did this with a twin with a low balance intentionally, well, because adhd, anyways when I came back to the dashboard it was showing 

- 87~ tft with 87 locked tft and contracts were in the grace period state. 

first, i tried to delete the contracts since i hadnt meant to leave them up in the first place and i got 

- Transaction error low balance return from chain notification
- contract deleted successfully dialog notification
- .0005 tft balance, 0 locked

second, i added 100 tft to the account and tried again to delete the contracts, 

- begin 99 tft balance, 0 locked 
- transaction error low balance
- some contracts deleted 
- 3 vms remaining
- contracts deleted successfully dialog notification
- end .0005 tft balance, 0 locked 

third i added 500 tft to the account, and started recording ;)

- begin 499 tft balance, 0 locked
- all contracts deleted 
- contracts successfully deleted dialog box 
- end 294 tft balance, 0 locked.  

- 

### What did you expect?

workloads to pause and billing stop when balance is 0 

### Dashboard info

https://user-images.githubusercontent.com/44621168/215297937-88ef321e-0842-43cc-972e-b8eaf34d60d3.mp4

**Comment by ramezsaeed** [comment]
Fixed on devnet and qanet,
will be updated on testnet and mainnet soon.

**Comment by A-Harby** [comment]
Verified Mainnet.
Grace period is fixed not billing and time is correct.
![image](https://user-images.githubusercontent.com/109473873/220936915-aa9deadf-ffb0-492e-ad36-dba966a3adf1.png)
