### ISSUE TITLE
[Bug 🐞]: nodes down after 3.8 upgrade

### ISSUE THREAD

**Issue by Parkers145** [threefoldtech/test_feedback#385]
### What happened?

After the 3.8 upgrade multiple people reported nodes down, 

I found main net node 5341 down in my farm in this state 

![B0FBCBBF-FE5B-4EC0-A9EC-703D30B80637](https://user-images.githubusercontent.com/44621168/220388371-e6c7596e-0466-42c6-b7e9-a700dca5cfd8.jpeg)

I restarted the node boot sequence was uneventful but did have one abnormality

![CFB54E92-F1F3-4CFD-86FF-D5471CD198C6](https://user-images.githubusercontent.com/44621168/220389183-53c3e9ec-45ae-4be9-a2a9-f0f7f97452dc.jpeg)

Ultimately the node came back up on reboot, but it looks like we only have 1700 nodes online down from 2900 yesterday so I suspect this is more widespread problem 

### What did you expect?

Node still up.

**Comment by Parkers145** [comment]
![image](https://user-images.githubusercontent.com/44621168/220392433-86ea81cc-d21d-4ed7-8189-5e0d11e1dc7f.jpeg)

This was pre restart logs

**Comment by jakubprogramming** [comment]
My two DIY nodes 5417 and 5418 are also affected (Dell PowerEdge Servers). They suddenly have gone offline. 
I am not on site, so I cannot check what the connected screen is showing. But the servers themselves are still connected to the internet, as I can see by checking my local networks router via VPN. 

Hope there will be a better solution than manually rebooting, but if thats the only way people need to be informed asap.

**Comment by muhamadazmy** [comment]
No, you don't have to reboot (at least not yet) hopefully after patching tfchain, the nodes will fix themselves

**Comment by Parkers145** [comment]
I had already rebooted when I created this issue and the issue has resolved on reboot. 

Just to be clear, I did not have the serial number registration issue. I'm not sure where gen came from in that convo but that was entirely separate conversation from what I was discussing

**Comment by muhamadazmy** [comment]
Okay, so sounds like that is a different issue with you than the other one i saw on the chat. Any chance we have the logs from before the node was down?

I will see if i can find the node logs from monitoring

**Comment by muhamadazmy** [comment]
![image](https://user-images.githubusercontent.com/10920323/220398930-b73e9e82-501d-48b3-a395-750b5b389fec.png)

I actually can't find anything abnormal in the logs before the node was rebooted. The new boot session was when ntp was first giving up logs.

**Comment by jvermond** [comment]
![16769964885928062169002478944027](https://user-images.githubusercontent.com/39809174/220401510-f9330150-66a6-4b7a-bd86-cb75e00eaa12.jpg)

**Comment by Parkers145** [comment]
I added my pre restart logs above

**Comment by jvermond** [comment]
So these are my logs, error does not seem to go away.

And as mentioned, this only affected Dell servers

**Comment by muhamadazmy** [comment]
All nodes should be back now. I will close it now but you can reopen if your node is still down
