### ISSUE TITLE
[Bug 🐞]: metrics.grid.tf Displays Node Addresses Instead of Node IDs

### ISSUE THREAD

**Issue by mohamedamer453** [threefoldtech/test_feedback#388]
### What happened?

metrics.grid.tf should use the node ID instead of using the node address.

![image](https://user-images.githubusercontent.com/101194226/223113404-d04cb332-38f0-4a28-ab1e-d7cee662a478.png)

Since it's very confusing for the user to select the node from a list of addresses however it is very simple to select a specific node id.

![image](https://user-images.githubusercontent.com/101194226/223113635-23e1900c-6d72-4772-bc11-432ae846c1de.png)

### What did you expect?

The Node Selection should display a list of Node IDs.

### What browsers are you seeing the problem on?

Chrome

**Comment by xmonader** [comment]
@0oM4R can you link the previous issue here

**Comment by xmonader** [comment]
closing with https://github.com/threefoldtech/tfgrid_dashboard/issues/452
