### ISSUE TITLE
[Bug 🐞]: The `Help` button in metrics.grid.tf redirects the user to the same page.

### ISSUE THREAD

**Issue by mohamedamer453** [threefoldtech/test_feedback#389]
### What happened?

The `Help` button in metrics.grid.tf redirects the user to the same page.

[Untitled_ Mar 6, 2023 2_49 PM.webm](https://user-images.githubusercontent.com/101194226/223115849-14cfd70e-4478-436d-bb3d-33cab4c10887.webm)

### What did you expect?

It should redirect the user to any help/manual/docs page instead of redirecting to the same page.

**Comment by rkhamis** [comment]
This is an issue in grafana

**Comment by coesensbert** [comment]
help button has been disabled for now

https://github.com/threefoldtech/tf_operations/issues/1502
