### ISSUE TITLE
[Bug 🐞]: Deployment on Playground (Mainnet), Receiving error: Undefined 

### ISSUE THREAD

**Issue by mik-tf** [threefoldtech/test_feedback#390]
### What happened?

You can see the discussion here:https://t.me/threefoldtesting/11005

In short, a user wanted to deploy a workload on the node 4550, but got the error: Undefined.
I tried to deploy on my side, and it worked on node 4550. (No undefined error)

I could then SSH with yggdrasil.

The workload was: Full VM, Planetary Network. Deploying on Brave browser.

I then deployed the same kind of workload on node 581. A 3node that never had a deployment or few.
Got the error Undefined. Retried a couple of times. After 3-4 times, the deployment was successful.
I could then also SSH with yggdrasil

So the problem is fixable with time and redeployment, but it is not efficient.

![undefined](https://user-images.githubusercontent.com/77026219/226644454-c9e825bf-63d7-4154-9cdb-4e9d8c842448.jpg)

### What did you expect?

The deployment should launch without sending the undefined error and having to redeploy a couple of times until it works.

### What browsers are you seeing the problem on?

Chrome

### ZOS info

It was a full vm deployment on a 3node without public IPv4. Just planetary network.

### Dashboard info

It was on play.grid.tf

### weblets info

Playground, full VM, ubuntu 22.04

**Comment by mohamedamer453** [comment]
Verified in https://github.com/threefoldtech/grid_weblets/issues/1398#issuecomment-1499032153

Also verified on devnet from a full vm deployment as originally mentioned in the issue and it was deployed without any errors.

![image](https://user-images.githubusercontent.com/101194226/230906249-a335b287-c89b-465e-8c2a-a3e330dc2a2f.png)

Will also verify it again once the fix reaches mainnet and reopen it if i was able to reproduce it there.

**Comment by despiegk** [comment]
Mik showed how the process is not reliable enough, just testing at your side is a good start but not good enough.

We need to try to find why can it fail, what do we do to make sure that eventually it does work, user experience needs to be good.
