### ISSUE TITLE
[Bug 🐞]: Contracts stuck in grace period on testnet

### ISSUE THREAD

**Issue by mohamedamer453** [threefoldtech/test_feedback#391]
### What happened?

Some of my contracts on testnet entered grace period a couple of days ago, since then i funded my account and some contracts were successfully resumed and i was able to access them at the time then i was able to delete them without any issues. however two of my contracts are still stuck in grace period `19303` & `19304` one of them is a rent contract for node `201` and the other is an owncloud deployment.

![image](https://user-images.githubusercontent.com/101194226/228506125-7cc1a022-32ea-48e0-bab8-68ea483278b8.png)

![image](https://user-images.githubusercontent.com/101194226/228506182-721f118c-4438-44d7-96ef-536f6532b4d5.png)

Also as it can be seen in the screenshot above i've already funded my account to cover all of the locked tokens and more but that did not change anything. and the amount of locked tokens also didn't change since yesterday.

> ***Note: both nodes `7` & `201` were restarted while these contracts were in grace period, the contracts that were on node `7` were resumed successfully and deleted after. but the rent contract for node `201` and the deployment on it are the ones that were not resumed till now.

### What did you expect?

The contracts should've been resumed by now since the account was funded.

### What browsers are you seeing the problem on?

Chrome

### weblets info

Testnet `v1.7.0-rc2`

**Comment by ramezsaeed** [comment]
@DylanVerstraete can you please check this one asap

**Comment by DylanVerstraete** [comment]
@mohamedamer453 You recharged the wallet with to few tokens. The total amount this rent contract costed since you created it until now is around 1K TFT.

**Comment by mohamedamer453** [comment]
Hmm ok i understand, however there's something that i quite don't. In the weblets it says that the billing rate for my rent contract is `~ 5.5` tft/hour and this contract was only alive for like 2 or 3 hours max before it entered grace period. does the calculation continue after the contact is paused and till i add more funds to my account?

**Comment by DylanVerstraete** [comment]
@mohamedamer453 indeed, regardless of the state of the contract, the amount due still accumulates since the resources are still in use by your contract and cannot be used by anyone else.

**Comment by mohamedamer453** [comment]
> @mohamedamer453 indeed, regardless of the state of the contract, the amount due still accumulates since the resources are still in use by your contract and cannot be used by anyone else.

Ok great, will close this one since it was a misunderstanding from my side and i created another issue in the weblets https://github.com/threefoldtech/tfgrid-sdk-ts/issues/80 to display the amount needed to unlock the contracts after its [function](https://github.com/threefoldtech/tfgrid-sdk-ts/issues/12) is implemented in the grid3_client_ts
