### ISSUE TITLE
[Bug 🐞]: Deployment on Playground (Mainnet), Receiving error: Error: Error getting node 5453: Error: Failed to send request to twinId 8543 with command: zos.statistics.get, payload: due to Didn't get a response after 60 seconds

### ISSUE THREAD

**Issue by shng4you** [threefoldtech/test_feedback#392]
### What happened?

The user wanted to deploy a workload on the node 5453, but got the error: Error: Failed to send request to twinId 8543 with command: zos.statistics.get, payload: due to Didn't get a response after 60 seconds
The user can't reach his node (which seems online according to the grid explorer) 5453. It is a gold farm. When he tries his other farm node 4000, it works fine. 
And I tried to deploy it on my side, and having the same error.
![Capture](https://user-images.githubusercontent.com/95933607/234297038-b9a89716-0981-43a6-8e04-64943d3d88f6.PNG)
![Node id 5453](https://user-images.githubusercontent.com/95933607/234289513-0b957ee8-1a53-4124-9936-50700302f379.PNG)

### What did you expect?

The deployment should launch without sending this error and having to redeploy a couple of times until it works.

### What browsers are you seeing the problem on?

Chrome

### Dashboard info

It was on play.grid.tf. 

### weblets info

Playground, full VM, ubuntu 22.04
Version: v1.7.0-rc3

**Comment by A-Harby** [comment]
Weblets Mainnet, v1.7.0.
I also tried to deploy a FullVM and got the same error.
![image](https://user-images.githubusercontent.com/109473873/236670826-9812ff32-9524-4e66-bdff-94ab5a052379.png)

But found something strange in the explorer node details, The node HRU resource is NA.
![image](https://user-images.githubusercontent.com/109473873/236670892-72f77f06-d2bd-4935-908e-ff236d2094d5.png)
And it says It have Zero HRU in the gridproxy
![image](https://user-images.githubusercontent.com/109473873/236670951-272ea3d0-fb9b-4ba1-abe0-4e16eb9c7b52.png)

It should not possible to depoly a node with a zero hru, that maybe be causing the error.

**Comment by AhmedHanafy725** [comment]
from the logs, it could set up the network at the beginning and get the required info from the node then it fails to get the deployment status after sending the deployment to the node, so it seems that the node sometimes returns the response before the timeout and sometimes does not.

**Comment by A-Harby** [comment]
Same [issue](https://github.com/threefoldtech/test_feedback/issues/393) in terraform with Node ID 5453

**Comment by xmonader** [comment]
please reopen if the issue stands
