### ISSUE TITLE
[Bug 🐞]: Global workload with the same name exists

### ISSUE THREAD

**Issue by mik-tf** [threefoldtech/test_feedback#395]
### What happened?

To reproduce the error:

On the Playground:

* I deployed a full vm with a name by the playground
* After some minutes, I had the error: deployment exceeded 5 minutes (or something like that, I didn't screenshot this, but that's the overall message)
* I clicked "back", then "deploy"
* So the VM had the same name for the deployment.
* Then I received this error: Global workload with the same name exists (see picture)

***
![error_message](https://github.com/threefoldtech/test_feedback/assets/77026219/fbf5a82e-eac4-4b20-9663-aa56ebccb5da)

### What did you expect?

I talked about this with @scottyeager 

He said: " There's something off about this, cause if the first workload failed, then the name should be available for reuse I would think. Or at least there's a UI/UX improvement to be made here"

**Comment by AhmedHanafy725** [comment]
which network was used (dev, test, or main)?

**Comment by mik-tf** [comment]
I think it was main net. Sorry for the late response. Just saw this!

**Comment by AhmedHanafy725** [comment]
this issue is resolved on devnet. the network workload wasn't rolled back

**Comment by A-Harby** [comment]
Closing the as it is fixed on weblets devnet after trying deploying some solution and error cannot be reproduced.
