### ISSUE TITLE
[Bug 🐞]: Cannot deploy a large VM with a large disk while the dashboard reports capacity available

### ISSUE THREAD

**Issue by weynandkuijpers** [threefoldtech/test_feedback#399]
### What happened?

DWS, a web3.0 cloud hosting company is using the Tf Grid for compute services.  They have tried to deploy a (large) VM which failed.  They contacted and and to recreate the issue I used the play.grid.tf and a terraform script to launch a vm with the following characteristics: 
- Cores: 24
- Memory: 163840
- Disk: 4096 GB

Both methods failed and came back with the error:
![error](https://github.com/threefoldtech/test_feedback/assets/13766992/318aae6a-8e10-4968-b0cf-a94f0805924b)

The dashboard reports there is plenty of SSD space available:
<img width="860" alt="image" src="https://github.com/threefoldtech/test_feedback/assets/13766992/61255d14-ec0a-4908-b3f6-1e1e8dbc5df8">

### What did you expect?

I expected the 4GB virtual disk to be provisioned.  I tapered the disk requirement down to 3TB [Failed], 2TB [Failed] and finally at 1TB (=1024GB) I could provision the VM's.

Monitoring shows that indeed I have provisioned 1TB:
<img width="832" alt="image" src="https://github.com/threefoldtech/test_feedback/assets/13766992/0c823826-b5ac-463c-a321-4d43501001b3">

But this is far from the reported upper limit of 7TB:
<img width="910" alt="image" src="https://github.com/threefoldtech/test_feedback/assets/13766992/f9b5e7cb-3edb-4d64-9c6e-0087e968c33e">

### What browsers are you seeing the problem on?

Chrome

### Dashboard info

<img width="910" alt="image" src="https://github.com/threefoldtech/test_feedback/assets/13766992/4e1470c0-ef9c-4dc0-8073-9fc379b6cda8">

**Comment by AhmedHanafy725** [comment]
opened an issue for it on the typescript sdk https://github.com/threefoldtech/tfgrid-sdk-ts/issues/864
