### ISSUE TITLE
TC176: Deploy Mount

### ISSUE THREAD

**Issue by georgeconstantinou** [threefoldtech/test_feedback#40]
If the disk is larges than the original drive (10 GB) fails with:

```
Error: error waiting deployment: workload 1 failed within deployment 2886 with error no space left on device
```

**Comment by xmonader** [comment]
How is the original disk related in this case?

Could be the node doesn't have resources to create the mount?

**Comment by ramezsaeed** [comment]
@georgeconstantinou please reproduce if this still valid

**Comment by rkhamis** [comment]
I'll close this. if it's still an issue @georgeconstantinou @mamchenkov please reopen
