### ISSUE TITLE
[Bug 🐞]: Error: failed to create contract: failed to create contract: error extracting events 

### ISSUE THREAD

**Issue by shng4you** [threefoldtech/test_feedback#410]
### What happened?

The farmer is trying to set up some nodes on Terraform. 
Farmer says: "Trying to set up some nodes on the grid yesterday, the same problem today again.

│ Error: failed to create contract: failed to create contract: error extracting events from block(0xc58415959c1226847381d8015a1e61b874e5a8edc84065a73df05252ec170bf5): failed to decode event: unable to find field Balances_Locked for event #37 with EventID [20 17]

### What did you expect?

Should have set up the node on the grid without any issues.

### ZOS info

No response

### Dashboard info

No response

### weblets info

No response

### Relevant log output

```shell
N/a
```

**Comment by rawdaGastan** [comment]
could you please check the version you use? is it v1.9.2?
