### ISSUE TITLE
[Bug 🐞]: Unable to migrate TF WordPress by using Blog Vault plugin. 

### ISSUE THREAD

**Issue by shng4you** [threefoldtech/test_feedback#411]
### What happened?

Error! The destination database could not be validated. Please check the destination WordPress and retry

### What did you expect?

Farmer request to whitelist the following IPs on the server to allow access to the site’s database and resume the migration process:
104.248.114.9
192.81.221.63
45.63.10.187
45.76.137.73

**Comment by ramezsaeed** [comment]
what do you mean by whitelist the following IPs ?
 how this related to wordpress migration.
please add more info about Blog vault plugin.

**Comment by shng4you** [comment]
> what do you mean by whitelist the following IPs ? how this related to wordpress migration. please add more info about Blog vault plugin.

The Farmer says: "I am using Brave browser, however BlogVault is not trying to connect with the help of my browser, the connection is made by their server. And Yes, I am attempting to deploy WordPress on the playground/Terraform environment. Wordpress is working fine and now I want to migrate my site as a test to experience how this would work out. Because I am working with Blog Vault I would like to use their migration solution, I have perfect experience with their tool here.
However, their tool had a problem with migration in this case and their support send me this message:
Could you please ask your WebHost to whitelist the below IPs on the server to provide access to the site's database and reinitiate the migration process?
104.248.114.9
192.81.221.63
45.63.10.187
45.76.137.73
Also, he got an error while migrating process: Error! The destination database could not be validated. Please check the destination WordPress and retry.

**Comment by TullysInc** [comment]
> what do you mean by whitelist the following IPs ? how this related to wordpress migration. please add more info about Blog vault plugin.

From some of the resources shared by Mik, it appears this doesn't require ThreeFold's intervention to fix and the migration the user is attempting maybe irrelevant to us, so we should be able to close this ticket.

Blog vault plugin is a tool that helps protect and secure a blog's data by creating backups, restoring previous versions, and providing security features to prevent hacking or data loss. It is used to safeguard the content and functionality of a blog.

There seems to be two ways to probably whitelist the ips. These resources have been shared with the user.

From wordpress: https://make.wordpress.org/meta/handbook/tutorials-guides/allow-listing-ip-addresses/

From blog: https://atonce.com/blog/how-to-whitelist-ip-on-wordpress
