### ISSUE TITLE
Is dashboard disclaimer still needed?

### ISSUE THREAD

**Issue by samtaggart** [threefoldtech/test_feedback#426]
<img width="1477" alt="Screenshot 2024-03-11 at 19 37 41" src="https://github.com/threefoldtech/test_feedback/assets/50134479/adcaa2ff-1060-4c08-8fc9-3d1850b0703d">

Is it still experimental if it is now on mainnet?

**Comment by ramezsaeed** [comment]
Already removed, and deployed n Mainnet now
