### ISSUE TITLE
TF Explorer Node Statistics

### ISSUE THREAD

**Issue by mohamedamer453** [threefoldtech/test_feedback#43]
On devnet the number of nodes shown in the statistics page is not the same as the number shown in data table in the nodes page.

The statistics page shows 216 node

![image](https://user-images.githubusercontent.com/101194226/158795811-162ac74f-c920-45f4-80e6-1e5078d1ffa4.png)

However the data table shows only 197 nodes with no filters applied

![nodes](https://user-images.githubusercontent.com/101194226/158798091-9fe0e3c8-9068-41cb-b583-90a0a8e263ce.png)

![image](https://user-images.githubusercontent.com/101194226/158798308-b7a1b76d-a723-4276-b575-025862a56945.png)

On testnet the same number is shown on both the statistics page and the data table.

**Comment by RafyAmgadBenjamin** [comment]
in the statistics page we got the data from grid proxy while the data in nodes page are from the graphql and it takes time to update the status of the nodes, I think that's why this is happening
