### ISSUE TITLE
[Bug 🐞]: To receive alerts when a deposit or withdrawal is made from the wallet.

### ISSUE THREAD

**Issue by shng4you** [threefoldtech/test_feedback#431]
### What happened?

Farmers/users are requesting to be notified when a deposit or withdrawal is made from the wallet.

### What did you expect?

Farmers/users are requesting to be notified when a deposit or withdrawal is made from the wallet.

**Comment by mik-tf** [comment]
Additional info:

# Situation

- As of now, if a user makes a transaction with their TF Connect app, they do not receive any notifications.
- If a user connects their tf connect wallet address to, e.g., Lobstr, Lobstr will send a notification alert every time there is a transaction with the wallet address.

# Feature Request

- Could we add a feature that would send a notification email when there is activity/transaction on the TF Connect app wallet?

# References

TF Support received feedback from the community where users asked for this feature.

**Comment by mik-tf** [comment]
Great issue. thanks @shng4you. I just redirect it to the threefold_connect repo.

https://github.com/threefoldtech/threefold_connect/issues/596
