### ISSUE TITLE
[Bug 🐞]: Show vm's ip in the contracts page

### ISSUE THREAD

**Issue by luthic** [threefoldtech/test_feedback#436]
### What happened?

To find the IP adress of my deployments I need to go into the menu to deploy a new node and then scroll all the way to the bottom

### What did you expect?

have the ip appear under the side menu: Contracts

**Comment by AhmedHanafy725** [comment]
The contracts page wasn't made to list the deployments the user has. it was done to see the contracts the user has on the grid and how much he pays for each contract and unlock the contract if it went in a grace period.
