### ISSUE TITLE
[Bug 🐞]: Left contract after deleting a vm

### ISSUE THREAD

**Issue by luthic** [threefoldtech/test_feedback#437]
### What happened?

 If I create a VPS it creates a second contract that I have to delete manually or it will just produce fees for nothing. 

### What did you expect?

Just create the one contract that I clicked for.

**Comment by AhmedHanafy725** [comment]
this contract is used for the network workload that the VM uses and deleting the solution page should delete this contract too

![delete](https://github.com/threefoldtech/test_feedback/assets/41957921/45c6293f-04be-4da2-ae4d-05685a476841)
