### ISSUE TITLE
TF Explorer no online nodes on testnet

### ISSUE THREAD

**Issue by mohamedamer453** [threefoldtech/test_feedback#44]
Grid Explorer shows that there are no online nodes on testnet

![image](https://user-images.githubusercontent.com/101194226/158802290-1319acf9-5df9-4e67-ad85-7d750ba4c518.png)

I tried deploying a vm through weblets on node 1 and it worked fine with no errors 

![image](https://user-images.githubusercontent.com/101194226/158802478-ef2e4e44-455d-4904-9e80-fb5b0af0466d.png)

```
{
    "version": 0,
    "contractId": 3627,
    "nodeId": 1,
    "name": "VM577a24a8",
    "created": 1647517451,
    "status": "ok",
    "message": "",
    "flist": "https://hub.grid.tf/tf-official-apps/threefoldtech-ubuntu-20.04.flist",
    "publicIP": null,
    "planetary": "300:2589:76ee:f44e:c73:5821:15dd:160c",
    "interfaces": [
        {
            "network": "NW59bc52c6",
            "ip": "10.20.2.2"
        }
    ],
    "capacity": {
        "cpu": 4,
        "memory": 8192
    },
    "mounts": [],
    "env": {
        "SSH_KEY": "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQC533B35CELELtgg2d7Tsi5KelLxR0FYUlrcTmRRQuTNP9arP01JYD8iHKqh6naMbbzR8+M0gdPEeRK4oVqQtEcH1C47vLyRI/4DqahAE2nTW08wtJM5uiIvcQ9H2HMzZ3MXYWWlgyHMgW2QXQxzrRS0NXvsY+4wxe97MMZs9MDs+d+X15DfG6JffjMHydi+4tHB50WmHe5tFscBFxLbgDBUxNGiwi3BQc1nWIuYwMMV1GFwT3ndyLAp19KPkEa/dffiqLdzkgs2qpXtfBhTZ/lFeQRc60DHCMWExr9ySDbavIMuBFylf/ZQeJXm9dFXJN7bBTbflZIIuUMjmrI7cU5eSuZqAj5l+Yb1mLN8ljmKSIM3/tkKbzXNH5AUtRVKTn+aEPvJAEYtserAxAP5pjy6nmegn0UerEE3DWEV2kqDig3aPSNhi9WSCykvG2tz7DIr0UP6qEIWYMC/5OisnSGj8w8dAjyxS9B0Jlx7DEmqPDNBqp8UcwV75Cot8vtIac= root@mohamed-Inspiron-3576"
    },
    "entrypoint": "/init.sh",
    "metadata": "",
    "description": "",
    "corex": false
}

```

![image](https://user-images.githubusercontent.com/101194226/158803310-529c4080-c2f8-4d50-9913-5d94e9271af3.png)

However in the explorer it shows that node 1 is offline and it has 0 resources.

![image](https://user-images.githubusercontent.com/101194226/158803044-71bad03b-f034-4348-80c9-79b6e5dac8b5.png)

**Comment by RafyAmgadBenjamin** [comment]
in nodes in explorer we depend on the data from graphql but the weblets depends on girdrpoxy,
After discussing this with @OmarElawady, we found that the data on graphql hasn't been updated for four days
that's why that happened 

https://github.com/threefoldtech/tf_operations/issues/760
