### ISSUE TITLE
Environment Variables not appearing in VMs on testnet

### ISSUE THREAD

**Issue by mohamedamer453** [threefoldtech/test_feedback#47]
When setting environment variables for a Vm either through weblets, Terraform, Ts_client. the environment variables are not found in the vm.

There is a closed [issue](https://github.com/threefoldtech/terraform-provider-grid/issues/113) discussing this, and mentioned in the issue that it's related to the used [image](https://hub.grid.tf/tf-official-apps/base:latest.flist) but after trying the [lightweight image](https://hub.grid.tf/tf-official-apps/base:latest.flist) and the same [Ubuntu image ](https://hub.grid.tf/omar0.3bot/omarelawady-ubuntu-20.04.flist) as mentioned in the issue the environment variables are still not found.

### Weblets
Starting with the weblets firstly using the mentioned Ubuntu flist and adding a test environment variable `TEST_VAR`

![image](https://user-images.githubusercontent.com/101194226/159274334-c08f715e-f157-4942-b430-6c4d71ca03a4.png)

VM Config: [Weblets_config.txt](https://github.com/threefoldtech/test_feedback/files/8315922/Weblets_config.txt)

Trying to print the environment variables using `env` or `printenv` or `set` or `echo $TEST_VAR` the test variable is not available.
all the logs for these commands are available here : [Weblets_logs.txt](https://github.com/threefoldtech/test_feedback/files/8316035/Weblets_logs.txt)

### Terraform

By adding a test environment variable
```
env_vars = {
      SSH_KEY = "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQC533B35CELELtgg2d7Tsi5KelLxR0FYUlrcTmRRQuTNP9arP01JYD8iHKqh6naMbbzR8+M0gdPEeRK4oVqQtEcH1C47vLyRI/4DqahAE2nTW08wtJM5uiIvcQ9H2HMzZ3MXYWWlgyHMgW2QXQxzrRS0NXvsY+4wxe97MMZs9MDs+d+X15DfG6JffjMHydi+4tHB50WmHe5tFscBFxLbgDBUxNGiwi3BQc1nWIuYwMMV1GFwT3ndyLAp19KPkEa/dffiqLdzkgs2qpXtfBhTZ/lFeQRc60DHCMWExr9ySDbavIMuBFylf/ZQeJXm9dFXJN7bBTbflZIIuUMjmrI7cU5eSuZqAj5l+Yb1mLN8ljmKSIM3/tkKbzXNH5AUtRVKTn+aEPvJAEYtserAxAP5pjy6nmegn0UerEE3DWEV2kqDig3aPSNhi9WSCykvG2tz7DIr0UP6qEIWYMC/5OisnSGj8w8dAjyxS9B0Jlx7DEmqPDNBqp8UcwV75Cot8vtIac= root@mohamed-Inspiron-3576"
      TEST_VAR = "this is a test"
    }
```
Config: [Terraform_Config.txt](https://github.com/threefoldtech/test_feedback/files/8316067/Terraform_Config.txt)

Trying to print the environment variables using `env` or `printenv` or `set` or `echo $TEST_VAR` the test variable is not available.
all the logs for these commands are available here : [Terraform_logs.txt](https://github.com/threefoldtech/test_feedback/files/8316209/Terraform_logs.txt)

### Ts_Client

By adding a test environment variable
```
vm.env = {
    SSH_KEY: config.ssh_key,
    TEST_VAR: "this is a test",
};
```
Config: [TsClient_Config.txt](https://github.com/threefoldtech/test_feedback/files/8316266/TsClient_Config.txt)

Trying to print the environment variables using `env` or `printenv` or `set` or `echo $TEST_VAR` the test variable is not available.
all the logs for these commands are available here : [TsClient_logs.txt](https://github.com/threefoldtech/test_feedback/files/8316340/TsClient_logs.txt)

***note: I also tried the same 3 cases using the [lightweight Image](https://hub.grid.tf/tf-official-apps/base:latest.flist) and I did not find the environment variables.

**Comment by AhmedHanafy725** [comment]
The environment variables can be only available for process id 1. As proof, you could ssh to the machine and login while the ssh key was passing in the environment variables

you can see them by this command
`cat /proc/1/environ | tr '\0' '\n'`

**Comment by mohamedamer453** [comment]
verified on devnet using weblets, terraform, ts_client with the mentioned command `cat /proc/1/environ | tr '\0' '\n'`
and the environment variables are there.
