### ISSUE TITLE
GETTFT: For the followup transaction does TFT get sent to the latest TFT address specified?

### ISSUE THREAD

**Issue by georgeconstantinou** [threefoldtech/test_feedback#51]
Geert is asking:
"There is no memo text at all to be added ? I specified now another TFT wallet address but the gettft address is exactly the same. How to make the difference between transfers ?"

Do we save only the latest TFT address specificed? what will happen if the user send BTC in a followup transaction to the same address?

**Comment by georgeconstantinou** [comment]
Moved from: https://circles.threefold.me/project/test-tfgrid3/issue/2

**Comment by xmonader** [comment]
We always used the latest.
