### ISSUE TITLE
logic for SSD in ZOS provisioning

### ISSUE THREAD

**Issue by georgeconstantinou** [threefoldtech/test_feedback#53]
see rules to be implemented in #6

* overprovisioning of 2x on SSD
* check size SSD capacity in line to CPU

github issue: [https://github.com/threefoldtech/zos/issues/1496](https://github.com/threefoldtech/zos/issues/1496)

**Comment by georgeconstantinou** [comment]
Moved from: https://circles.threefold.me/project/test-tfgrid3/issue/7

**Comment by rkhamis** [comment]
already done
