### ISSUE TITLE
tried to remove vm from terraform

### ISSUE THREAD

**Issue by georgeconstantinou** [threefoldtech/test_feedback#58]
```bash
│ Error: error sending deployment to the node: workload 'zmachine' does not support upgrade: upgrade validation error
```

just remove a vm from the 2, and try to apply will not work

this should be possible
[main.zip](https://github.com/threefoldtech/tfchain_explorer/files/8408662/main.zip)

Moved from: https://circles.threefold.me/project/test-tfgrid3/issue/92

**Comment by rkhamis** [comment]
most likey along with the removal of the vm, there were changes in the properties in the other vm, which isn't allowed in zos side yet


wil close
