### ISSUE TITLE
Weblet in node filter: limits the country and farms

### ISSUE THREAD

**Issue by georgeconstantinou** [threefoldtech/test_feedback#59]
it's better if show all farms and country that have node

why i can see all farms and countries and most of them don't have nodes?

Relates to: https://github.com/threefoldtech/grid_weblets/issues/176

Moved from: https://circles.threefold.me/project/test-tfgrid3/issue/61

**Comment by rkhamis** [comment]
FR: https://github.com/threefoldtech/grid_weblets/issues/176

will close this one to avoid duplication
