### ISSUE TITLE
TF Connect issues

### ISSUE THREAD

**Issue by georgeconstantinou** [threefoldtech/test_feedback#62]
https://github.com/threefoldtech/threefold_connect/issues/324 
https://github.com/threefoldtech/threefold_connect/issues/354 
https://github.com/threefoldtech/threefold_connect/issues/363

https://github.com/threefoldtech/threefold_connect/issues/360

Moved from: https://circles.threefold.me/project/test-tfgrid3/issue/52

**Comment by ramezsaeed** [comment]
@ken-de-moor @georgeconstantinou 
is this still valid ??

**Comment by ken-de-moor** [comment]
All the linked issues are closed, so shouldn't be relevant anymore. 3.6 is live as well.
