### ISSUE TITLE
i cannot find VMs on deployment in weblet after deployment with terraform

### ISSUE THREAD

**Issue by georgeconstantinou** [threefoldtech/test_feedback#67]
did a deploy of terraform, 2 machines were created

could not find them in deployments of VM's on  
https://play.grid.tf/#/deployedlist

this means that not all contracts are shown !!!

```bash
Outputs:

node1_vm1_ip = "10.1.3.2"
node1_vm2_ip = "10.1.3.3"
public_ip = "185.206.122.151/24"
wg_config = <<EOT

[Interface]
Address = 100.64.1.2
PrivateKey = sGkZ1nFIvAOntWeIuONJlkZLmmasSdoP0DhwZ9njeFI=
[Peer]
PublicKey = SjsSY9qp7LRK5DG5dG+jol++zrSry2Th1/CkTS5VuBw=
AllowedIPs = 10.1.0.0/16, 100.64.0.0/16
PersistentKeepalive = 25
Endpoint = 185.206.122.131:6689

EOT
```

Moved from: https://circles.threefold.me/project/test-tfgrid3/issue/93

**Comment by xmonader** [comment]
this is expected, given that terraform is storing the data on terraform state file, unlike the weblets that's activating the blockchain database storage for the state.
