### ISSUE TITLE
all 3nodes report "close to or 100%" HRU usage

### ISSUE THREAD

**Issue by weynandkuijpers** [threefoldtech/test_feedback#7]
All the 3nodes on the mainnet and test have close to a 100% HRU utilisation.

![image](https://user-images.githubusercontent.com/13766992/155319743-7413858b-5404-4a8f-a073-9009ae19059e.png)

![image](https://user-images.githubusercontent.com/13766992/155319800-e80b8808-b48f-4811-a401-e4faad5bb9c7.png)

![image](https://user-images.githubusercontent.com/13766992/155319938-e034bb48-2a9c-4189-adb7-4bde47741f7e.png)

etc etc,,,,

**Comment by weynandkuijpers** [comment]
![image](https://user-images.githubusercontent.com/13766992/155320082-501a854f-33d2-4be2-8e3c-4d5c7fc3dcac.png)

![image](https://user-images.githubusercontent.com/13766992/155320128-e578c120-bbf0-48da-9b60-16ecf35d5bbe.png)

**Comment by rkhamis** [comment]
no longer an issue
