### ISSUE TITLE
terraform, when node which doesn't exist no good error

### ISSUE THREAD

**Issue by georgeconstantinou** [threefoldtech/test_feedback#70]
```bash
╷
│ Error: couldn't reach node 4: non ok return code: 400, body: {"status": "error", "message": "Post "http://300:e24d:6667:8ced::1:8051/zbus-cmd": dial tcp [300:e24d:6667:8ced::1]:8051: i/o timeout"}
│
│ with grid_network.net1,
│ on main.tf line 16, in resource "grid_network" "net1":
│ 16: resource "grid_network" "net1" {
│
```

issue was I had a terraform file with node which did not exist, this throws a bad error, this is not understandeable

QUESTION

* do we check resources per node before we deploy?
* if resources not enough or node does not exist, do we warn?

Moved from: https://circles.threefold.me/project/test-tfgrid3/issue/89
Relates to: 
- https://github.com/threefoldtech/terraform-provider-grid/issues/144
- https://github.com/threefoldtech/terraform-provider-grid/issues/145

**Comment by rkhamis** [comment]
tracked in https://github.com/threefoldtech/terraform-provider-grid/issues/144
