### ISSUE TITLE
Statistics show all nodes, also the ones that were disconnected

### ISSUE THREAD

**Issue by georgeconstantinou** [threefoldtech/test_feedback#72]
See attachment:

- mainnet statistics shows 402 nodes but only 111 are online.
- testnet statistics shows 181 nodes but only 18 are online (a lot of nodes have already been migrated to mainnet).

So ALL the statistics need only to take up what is available online, not the history.

![image](https://user-images.githubusercontent.com/1926811/162705119-5f140b92-501e-4a27-97a6-6e55ada79e71.png)

![image](https://user-images.githubusercontent.com/1926811/162705204-cdc8464a-91f7-483f-88e8-01e97df12793.png)

Moved from: https://circles.threefold.me/project/test-tfgrid3/issue/155

**Comment by rkhamis** [comment]
@georgeconstantinou should be good now. please reopen if you find further issues with this
