### ISSUE TITLE
TC307: 1000 VMs

### ISSUE THREAD

**Issue by georgeconstantinou** [threefoldtech/test_feedback#75]
Error: couldn't generate deployments data: failed to assign node ips: failed to find free ip for VM: all ips are used

Moved from: https://circles.threefold.me/project/test-tfgrid3/issue/185

**Comment by mohamedamer453** [comment]
Closing this issue since all the issues about the test cases related to 1000VMs (TC307 -> TC310) are being followed [here](https://github.com/threefoldtech/terraform-provider-grid/issues/212)
