### ISSUE TITLE
Pending test cases

### ISSUE THREAD

**Issue by georgeconstantinou** [threefoldtech/test_feedback#81]
Below is a list of test cases we just added on test lodge, for **all remaining** required items that had no test cases linked to them.

These test cases **need to** be expanded and clarified as currently is unclear how we should proceed with running them:

* [TC433](https://app.testlodge.com/a/26076/projects/40893/suites/195671?expand_section=310550#case_3429048)
* [TC436](https://app.testlodge.com/a/26076/projects/40893/suites/193854?expand_section=305793#case_3429051)
* [TC437](https://app.testlodge.com/a/26076/projects/40893/suites/193854?expand_section=305793#case_3429052)
* [TC441](https://app.testlodge.com/a/26076/projects/40893/suites/194376?expand_section=307354#case_3429057)

Moved from: https://circles.threefold.me/project/test-tfgrid3/issue/151

**Comment by mohamedamer453** [comment]
Test cases Updated.

### [TC433](https://app.testlodge.com/a/26076/projects/40893/suites/195671?expand_section=310550#case_3429048)

TC433 was updated and test steps were added according to the requirement that it verifies [REQ191](https://app.testlodge.com/a/26076/projects/40893/requirements/38034#item_208006) 

### TC436, TC437, TC441

After further investigation and discussion with @xmonader These cases were removed from their test suites as they were not supposed to be test cases and they're just documentation requirements.

Please reopen this issue if there's a problem with the mentioned cases.
