### ISSUE TITLE
TFGrid Weblets: v1.3.1

### ISSUE THREAD

**Issue by dmitri-alleo** [threefoldtech/test_feedback#85]
Cannot see such options: 
- enable add Access to the network
- Apply capacity packages on Weblets
- Add presearch Weblets
- apply capacity packages on presearch

Those are not clear, what it should actually be:
- add validations on some name fields
- Reformat some fields and fix validation messages
- Fix workflow building issue
- new naming rules

Wondering if it can make the contract active, but not been able to delete it (this issue was reported previously)
- delete all deployment contracts

**Comment by rkhamis** [comment]
@dmitri-alleo I don't understand what you want here
