### ISSUE TITLE
Deploying OwnCloud

### ISSUE THREAD

**Issue by dmitri-alleo** [threefoldtech/test_feedback#87]
No matter which node I specify to deploy, 

I get this error

![image](https://user-images.githubusercontent.com/65153287/163328956-0138f308-19d4-4e2b-8c18-e84b1e4e9564.png)

As I have noticed this strange occurrence took place,  no nodes were showing as online for the Testnet

![image](https://user-images.githubusercontent.com/65153287/163329227-dfc221e0-b27a-4a77-920c-1523e369988a.png)

**Comment by rkhamis** [comment]
@dmitri-alleo testnet is back. please reopen if there are further issues
