### ISSUE TITLE
Caprover: Deploying a node on Threefold grid

### ISSUE THREAD

**Issue by mohamedamer453** [threefoldtech/test_feedback#96]
Each time i try to deploy a node on Threefold grid through Caprover i get this error.

```
Error
An error occurred while trying to deploy a worker node:
Error: Couldn't get free Wireguard ports for node 7 due to Error: Error: Request failed with status code 400
```

![image](https://user-images.githubusercontent.com/101194226/163829553-1d86ba6d-a221-4da3-89d0-7e53a4cffa03.png)

I tried deploying on multiple nodes that have available resources and i still got the same error.

The Caprover instance was deployed on testnet through weblets v1.3.2

**Comment by xmonader** [comment]
@abom please check

**Comment by abom** [comment]
This should be fixed now, can you try again? (note, you'll have to deploy a new caprover because some client versions were outdated after some graphql changes).

**Comment by xmonader** [comment]
I'll close and if still an issue please reopen @mohamedamer453

**Comment by mohamedamer453** [comment]
Verified on testnet  Weblets v1.4.1-rc2

It's fixed and working now and i was able to deploy a node.

![image](https://user-images.githubusercontent.com/101194226/164467019-51b23b68-50c2-4244-98cb-b3d6b07431f5.png)

![image](https://user-images.githubusercontent.com/101194226/164467120-8e8c7316-b3c2-464f-922a-13c7240f332e.png)
