### ISSUE TITLE
Testnet overloaded

### ISSUE THREAD

**Issue by dmitri-alleo** [threefoldtech/test_feedback#97]
Today it is very difficult to provision any resource on the Testnet,
as nodes show the error that they don't have enough resources/not available

Just found a node (node 3) with enough resources and by the time I have configured the naming, disks and test variables,
roughly about two minutes, the node was gone again.

Ideally it would be great if you could see the list of the nodes and resources wise which are available, or something like that,
instead of going through it manually trying to guess and catch a node

**Comment by xmonader** [comment]
You can always use the capacity planner to specify the resources you need e.g from terraform or from typescript client.

**Comment by dmitri-alleo** [comment]
No, I need to test the Weblets functionality.
I see what's the issue now, this happens specifically when I try to enable IPv4 for the VM

**Comment by dmitri-alleo** [comment]
Typescript client also doesn't work with the latest version,
The issue was reported last week

**Comment by xmonader** [comment]
@dmitri-alleo please be more specific, specially the workflows are always working for the grid3 client
